TARGET = pyrcc4
TEMPLATE = app
QT -= gui
QT += xml
CONFIG += warn_on release
CONFIG -= app_bundle
CONFIG -= android_install
target.path = /Users/saitadikonda/Desktop/TestingFolder/venv/bin/../bin
INSTALLS += target
INCLUDEPATH += /Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/pyrcc
VPATH = /Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/pyrcc
HEADERS = rcc.h
SOURCES = main.cpp rcc.cpp