/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19
 *
 * Copyright (c) 2016 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt4.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#ifndef _phononAPI_H
#define _phononAPI_H

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Deprecated_5_0
#define SIP_FEATURE_PyQt_NoOpenGLES
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_SystemTrayIcon
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SizeGrip
#define SIP_FEATURE_PyQt_OpenSSL
#define SIP_FEATURE_Py_DateTime
#define SIP_FEATURE_PyQt_NoQtPrintRangeBug
#define SIP_FEATURE_PyQt_WhatsThis
#define SIP_FEATURE_PyQt_ToolTip
#define SIP_FEATURE_PyQt_StatusTip
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_MACX
#define SIP_TIMELINE_Qt_4_8_7


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_0 0
#define sipName_0 &sipStrings_phonon[0]
#define sipNameNr_Phonon__BackendCapabilities__Notifier 39
#define sipName_Phonon__BackendCapabilities__Notifier &sipStrings_phonon[39]
#define sipNameNr_availableAudioCaptureDevicesChanged 77
#define sipName_availableAudioCaptureDevicesChanged &sipStrings_phonon[77]
#define sipNameNr_113 113
#define sipName_113 &sipStrings_phonon[113]
#define sipNameNr_availableAudioOutputDevicesChanged 148
#define sipName_availableAudioOutputDevicesChanged &sipStrings_phonon[148]
#define sipNameNr_183 183
#define sipName_183 &sipStrings_phonon[183]
#define sipNameNr_Phonon__MediaController__Features 217
#define sipName_Phonon__MediaController__Features &sipStrings_phonon[217]
#define sipNameNr_251 251
#define sipName_251 &sipStrings_phonon[251]
#define sipNameNr_284 284
#define sipName_284 &sipStrings_phonon[284]
#define sipNameNr_Phonon__VideoWidget__AspectRatio 317
#define sipName_Phonon__VideoWidget__AspectRatio &sipStrings_phonon[317]
#define sipNameNr_Phonon__MediaController__Feature 350
#define sipName_Phonon__MediaController__Feature &sipStrings_phonon[350]
#define sipNameNr_Phonon__AudioChannelDescription 383
#define sipName_Phonon__AudioChannelDescription &sipStrings_phonon[383]
#define sipNameNr_415 415
#define sipName_415 &sipStrings_phonon[415]
#define sipNameNr_Phonon__VideoWidget__ScaleMode 446
#define sipName_Phonon__VideoWidget__ScaleMode &sipStrings_phonon[446]
#define sipNameNr_Phonon__EffectDescriptionModel 477
#define sipName_Phonon__EffectDescriptionModel &sipStrings_phonon[477]
#define sipNameNr_Phonon__AudioOutputDeviceModel 508
#define sipName_Phonon__AudioOutputDeviceModel &sipStrings_phonon[508]
#define sipNameNr_Phonon__ObjectDescriptionModel 539
#define sipName_Phonon__ObjectDescriptionModel &sipStrings_phonon[539]
#define sipNameNr_Phonon__EffectParameter__Hints 570
#define sipName_Phonon__EffectParameter__Hints &sipStrings_phonon[570]
#define sipNameNr_availableAudioChannelsChanged 601
#define sipName_availableAudioChannelsChanged &sipStrings_phonon[601]
#define sipNameNr_Phonon__EffectParameter__Hint 631
#define sipName_Phonon__EffectParameter__Hint &sipStrings_phonon[631]
#define sipNameNr_availableAudioCaptureDevices 661
#define sipName_availableAudioCaptureDevices &sipStrings_phonon[661]
#define sipNameNr_PyQt4_QtCore_pyqtWrapperType 690
#define sipName_PyQt4_QtCore_pyqtWrapperType &sipStrings_phonon[690]
#define sipNameNr_Phonon__SubtitleDescription 719
#define sipName_Phonon__SubtitleDescription &sipStrings_phonon[719]
#define sipNameNr_availableAudioOutputDevices 747
#define sipName_availableAudioOutputDevices &sipStrings_phonon[747]
#define sipNameNr_Phonon__BackendCapabilities 775
#define sipName_Phonon__BackendCapabilities &sipStrings_phonon[775]
#define sipNameNr_Phonon__AbstractVideoOutput 803
#define sipName_Phonon__AbstractVideoOutput &sipStrings_phonon[803]
#define sipNameNr_Phonon__AbstractAudioOutput 831
#define sipName_Phonon__AbstractAudioOutput &sipStrings_phonon[831]
#define sipNameNr_859 859
#define sipName_859 &sipStrings_phonon[859]
#define sipNameNr_886 886
#define sipName_886 &sipStrings_phonon[886]
#define sipNameNr_913 913
#define sipName_913 &sipStrings_phonon[913]
#define sipNameNr_Phonon__AudioCaptureDevice 940
#define sipName_Phonon__AudioCaptureDevice &sipStrings_phonon[940]
#define sipNameNr_MusicBrainzDiscIdMetaData 967
#define sipName_MusicBrainzDiscIdMetaData &sipStrings_phonon[967]
#define sipNameNr_tupleIndexAtPositionIndex 993
#define sipName_tupleIndexAtPositionIndex &sipStrings_phonon[993]
#define sipNameNr_Phonon__EffectDescription 1019
#define sipName_Phonon__EffectDescription &sipStrings_phonon[1019]
#define sipNameNr_Phonon__AudioOutputDevice 1045
#define sipName_Phonon__AudioOutputDevice &sipStrings_phonon[1045]
#define sipNameNr_Phonon__ObjectDescription 1071
#define sipName_Phonon__ObjectDescription &sipStrings_phonon[1071]
#define sipNameNr_Phonon__MediaSource__Type 1097
#define sipName_Phonon__MediaSource__Type &sipStrings_phonon[1097]
#define sipNameNr_availableSubtitlesChanged 1123
#define sipName_availableSubtitlesChanged &sipStrings_phonon[1123]
#define sipNameNr_availableChaptersChanged 1149
#define sipName_availableChaptersChanged &sipStrings_phonon[1149]
#define sipNameNr_AudioChannelDescription 391
#define sipName_AudioChannelDescription &sipStrings_phonon[391]
#define sipNameNr_Phonon__MediaController 1174
#define sipName_Phonon__MediaController &sipStrings_phonon[1174]
#define sipNameNr_Phonon__EffectParameter 1198
#define sipName_Phonon__EffectParameter &sipStrings_phonon[1198]
#define sipNameNr_1222 1222
#define sipName_1222 &sipStrings_phonon[1222]
#define sipNameNr_EffectDescriptionModel 485
#define sipName_EffectDescriptionModel &sipStrings_phonon[485]
#define sipNameNr_AudioOutputDeviceModel 516
#define sipName_AudioOutputDeviceModel &sipStrings_phonon[516]
#define sipNameNr_ObjectDescriptionModel 547
#define sipName_ObjectDescriptionModel &sipStrings_phonon[547]
#define sipNameNr_setCurrentAudioChannel 1245
#define sipName_setCurrentAudioChannel &sipStrings_phonon[1245]
#define sipNameNr_availableAudioChannels 1268
#define sipName_availableAudioChannels &sipStrings_phonon[1268]
#define sipNameNr_availableTitlesChanged 1291
#define sipName_availableTitlesChanged &sipStrings_phonon[1291]
#define sipNameNr_availableAnglesChanged 1314
#define sipName_availableAnglesChanged &sipStrings_phonon[1314]
#define sipNameNr_windowActivationChange 1337
#define sipName_windowActivationChange &sipStrings_phonon[1337]
#define sipNameNr_AccessibilityCategory 1360
#define sipName_AccessibilityCategory &sipStrings_phonon[1360]
#define sipNameNr_CommunicationCategory 1382
#define sipName_CommunicationCategory &sipStrings_phonon[1382]
#define sipNameNr_availableAudioEffects 1404
#define sipName_availableAudioEffects &sipStrings_phonon[1404]
#define sipNameNr_mouseDoubleClickEvent 1426
#define sipName_mouseDoubleClickEvent &sipStrings_phonon[1426]
#define sipNameNr_Phonon__VolumeSlider 1448
#define sipName_Phonon__VolumeSlider &sipStrings_phonon[1448]
#define sipNameNr_NotificationCategory 1469
#define sipName_NotificationCategory &sipStrings_phonon[1469]
#define sipNameNr_prefinishMarkReached 1490
#define sipName_prefinishMarkReached &sipStrings_phonon[1490]
#define sipNameNr_currentSourceChanged 1511
#define sipName_currentSourceChanged &sipStrings_phonon[1511]
#define sipNameNr_Phonon__EffectWidget 1532
#define sipName_Phonon__EffectWidget &sipStrings_phonon[1532]
#define sipNameNr_isLogarithmicControl 1553
#define sipName_isLogarithmicControl &sipStrings_phonon[1553]
#define sipNameNr_supportedDropActions 1574
#define sipName_supportedDropActions &sipStrings_phonon[1574]
#define sipNameNr_1595 1595
#define sipName_1595 &sipStrings_phonon[1595]
#define sipNameNr_Phonon__VideoWidget 1615
#define sipName_Phonon__VideoWidget &sipStrings_phonon[1615]
#define sipNameNr_Phonon__VideoPlayer 1635
#define sipName_Phonon__VideoPlayer &sipStrings_phonon[1635]
#define sipNameNr_DescriptionMetaData 1655
#define sipName_DescriptionMetaData &sipStrings_phonon[1655]
#define sipNameNr_TracknumberMetaData 1675
#define sipName_TracknumberMetaData &sipStrings_phonon[1675]
#define sipNameNr_SubtitleDescription 727
#define sipName_SubtitleDescription &sipStrings_phonon[727]
#define sipNameNr_Phonon__MediaSource 1695
#define sipName_Phonon__MediaSource &sipStrings_phonon[1695]
#define sipNameNr_Phonon__MediaObject 1715
#define sipName_Phonon__MediaObject &sipStrings_phonon[1715]
#define sipNameNr_currentAudioChannel 1735
#define sipName_currentAudioChannel &sipStrings_phonon[1735]
#define sipNameNr_isMimeTypeAvailable 1755
#define sipName_isMimeTypeAvailable &sipStrings_phonon[1755]
#define sipNameNr_capabilitiesChanged 1775
#define sipName_capabilitiesChanged &sipStrings_phonon[1775]
#define sipNameNr_BackendCapabilities 783
#define sipName_BackendCapabilities &sipStrings_phonon[783]
#define sipNameNr_outputDeviceChanged 1795
#define sipName_outputDeviceChanged &sipStrings_phonon[1795]
#define sipNameNr_Phonon__AudioOutput 1815
#define sipName_Phonon__AudioOutput &sipStrings_phonon[1815]
#define sipNameNr_AbstractVideoOutput 811
#define sipName_AbstractVideoOutput &sipStrings_phonon[811]
#define sipNameNr_AbstractAudioOutput 839
#define sipName_AbstractAudioOutput &sipStrings_phonon[839]
#define sipNameNr_defaultButtonNumber 1835
#define sipName_defaultButtonNumber &sipStrings_phonon[1835]
#define sipNameNr_Phonon__SeekSlider 1855
#define sipName_Phonon__SeekSlider &sipStrings_phonon[1855]
#define sipNameNr_AudioCaptureDevice 948
#define sipName_AudioCaptureDevice &sipStrings_phonon[948]
#define sipNameNr_setCurrentSubtitle 1874
#define sipName_setCurrentSubtitle &sipStrings_phonon[1874]
#define sipNameNr_availableSubtitles 1893
#define sipName_availableSubtitles &sipStrings_phonon[1893]
#define sipNameNr_availableMimeTypes 1912
#define sipName_availableMimeTypes &sipStrings_phonon[1912]
#define sipNameNr_escapeButtonNumber 1931
#define sipName_escapeButtonNumber &sipStrings_phonon[1931]
#define sipNameNr_focusNextPrevChild 1950
#define sipName_focusNextPrevChild &sipStrings_phonon[1950]
#define sipNameNr_AspectRatioWidget 1969
#define sipName_AspectRatioWidget &sipStrings_phonon[1969]
#define sipNameNr_Phonon__ErrorType 1987
#define sipName_Phonon__ErrorType &sipStrings_phonon[1987]
#define sipNameNr_EffectDescription 1027
#define sipName_EffectDescription &sipStrings_phonon[1027]
#define sipNameNr_AudioOutputDevice 1053
#define sipName_AudioOutputDevice &sipStrings_phonon[1053]
#define sipNameNr_ObjectDescription 1079
#define sipName_ObjectDescription &sipStrings_phonon[1079]
#define sipNameNr_setTransitionTime 2005
#define sipName_setTransitionTime &sipStrings_phonon[2005]
#define sipNameNr_setAutoplayTitles 2023
#define sipName_setAutoplayTitles &sipStrings_phonon[2023]
#define sipNameNr_setCurrentChapter 2041
#define sipName_setCurrentChapter &sipStrings_phonon[2041]
#define sipNameNr_availableChapters 2059
#define sipName_availableChapters &sipStrings_phonon[2059]
#define sipNameNr_supportedFeatures 2077
#define sipName_supportedFeatures &sipStrings_phonon[2077]
#define sipNameNr_setParameterValue 2095
#define sipName_setParameterValue &sipStrings_phonon[2095]
#define sipNameNr_Phonon__MediaNode 2113
#define sipName_Phonon__MediaNode &sipStrings_phonon[2113]
#define sipNameNr_mouseReleaseEvent 2131
#define sipName_mouseReleaseEvent &sipStrings_phonon[2131]
#define sipNameNr_sip_simplewrapper 2149
#define sipName_sip_simplewrapper &sipStrings_phonon[2149]
#define sipNameNr_setMaximumVolume 2167
#define sipName_setMaximumVolume &sipStrings_phonon[2167]
#define sipNameNr_categoryToString 2184
#define sipName_categoryToString &sipStrings_phonon[2184]
#define sipNameNr_Phonon__Category 2201
#define sipName_Phonon__Category &sipStrings_phonon[2201]
#define sipNameNr_Phonon__MetaData 2218
#define sipName_Phonon__MetaData &sipStrings_phonon[2218]
#define sipNameNr_Phonon__DiscType 2235
#define sipName_Phonon__DiscType &sipStrings_phonon[2235]
#define sipNameNr_totalTimeChanged 2252
#define sipName_totalTimeChanged &sipStrings_phonon[2252]
#define sipNameNr_setPrefinishMark 2269
#define sipName_setPrefinishMark &sipStrings_phonon[2269]
#define sipNameNr_setCurrentSource 2286
#define sipName_setCurrentSource &sipStrings_phonon[2286]
#define sipNameNr_setVolumeDecibel 2303
#define sipName_setVolumeDecibel &sipStrings_phonon[2303]
#define sipNameNr_contextMenuEvent 2320
#define sipName_contextMenuEvent &sipStrings_phonon[2320]
#define sipNameNr_inputMethodEvent 2337
#define sipName_inputMethodEvent &sipStrings_phonon[2337]
#define sipNameNr_inputMethodQuery 2354
#define sipName_inputMethodQuery &sipStrings_phonon[2354]
#define sipNameNr_disconnectNotify 2371
#define sipName_disconnectNotify &sipStrings_phonon[2371]
#define sipNameNr_enterFullScreen 2388
#define sipName_enterFullScreen &sipStrings_phonon[2388]
#define sipNameNr_AspectRatio16_9 2404
#define sipName_AspectRatio16_9 &sipStrings_phonon[2404]
#define sipNameNr_AspectRatioAuto 2420
#define sipName_AspectRatioAuto &sipStrings_phonon[2420]
#define sipNameNr_tupleIndexOrder 2436
#define sipName_tupleIndexOrder &sipStrings_phonon[2436]
#define sipNameNr_hasVideoChanged 2452
#define sipName_hasVideoChanged &sipStrings_phonon[2452]
#define sipNameNr_seekableChanged 2468
#define sipName_seekableChanged &sipStrings_phonon[2468]
#define sipNameNr_metaDataChanged 2484
#define sipName_metaDataChanged &sipStrings_phonon[2484]
#define sipNameNr_currentSubtitle 2500
#define sipName_currentSubtitle &sipStrings_phonon[2500]
#define sipNameNr_setCurrentTitle 2516
#define sipName_setCurrentTitle &sipStrings_phonon[2516]
#define sipNameNr_setCurrentAngle 2532
#define sipName_setCurrentAngle &sipStrings_phonon[2532]
#define sipNameNr_availableTitles 2548
#define sipName_availableTitles &sipStrings_phonon[2548]
#define sipNameNr_availableAngles 2564
#define sipName_availableAngles &sipStrings_phonon[2564]
#define sipNameNr_MediaController 1182
#define sipName_MediaController &sipStrings_phonon[1182]
#define sipNameNr_LogarithmicHint 2580
#define sipName_LogarithmicHint &sipStrings_phonon[2580]
#define sipNameNr_EffectParameter 1206
#define sipName_EffectParameter &sipStrings_phonon[1206]
#define sipNameNr_setOutputDevice 2596
#define sipName_setOutputDevice &sipStrings_phonon[2596]
#define sipNameNr_setTickInterval 2612
#define sipName_setTickInterval &sipStrings_phonon[2612]
#define sipNameNr_aspectRatioMode 2628
#define sipName_aspectRatioMode &sipStrings_phonon[2628]
#define sipNameNr_deviceTransform 2644
#define sipName_deviceTransform &sipStrings_phonon[2644]
#define sipNameNr_minimumSizeHint 2660
#define sipName_minimumSizeHint &sipStrings_phonon[2660]
#define sipNameNr_mousePressEvent 2676
#define sipName_mousePressEvent &sipStrings_phonon[2676]
#define sipNameNr_keyReleaseEvent 2692
#define sipName_keyReleaseEvent &sipStrings_phonon[2692]
#define sipNameNr_setAudioOutput 2708
#define sipName_setAudioOutput &sipStrings_phonon[2708]
#define sipNameNr_setMuteVisible 2723
#define sipName_setMuteVisible &sipStrings_phonon[2723]
#define sipNameNr_setAspectRatio 2738
#define sipName_setAspectRatio &sipStrings_phonon[2738]
#define sipNameNr_exitFullScreen 2753
#define sipName_exitFullScreen &sipStrings_phonon[2753]
#define sipNameNr_AspectRatio4_3 2768
#define sipName_AspectRatio4_3 &sipStrings_phonon[2768]
#define sipNameNr_setMediaObject 2783
#define sipName_setMediaObject &sipStrings_phonon[2783]
#define sipNameNr_setIconVisible 2798
#define sipName_setIconVisible &sipStrings_phonon[2798]
#define sipNameNr_BufferingState 2813
#define sipName_BufferingState &sipStrings_phonon[2813]
#define sipNameNr_ArtistMetaData 2828
#define sipName_ArtistMetaData &sipStrings_phonon[2828]
#define sipNameNr_transitionTime 2843
#define sipName_transitionTime &sipStrings_phonon[2843]
#define sipNameNr_chapterChanged 2858
#define sipName_chapterChanged &sipStrings_phonon[2858]
#define sipNameNr_autoplayTitles 2873
#define sipName_autoplayTitles &sipStrings_phonon[2873]
#define sipNameNr_currentChapter 2888
#define sipName_currentChapter &sipStrings_phonon[2888]
#define sipNameNr_possibleValues 2903
#define sipName_possibleValues &sipStrings_phonon[2903]
#define sipNameNr_parameterValue 2918
#define sipName_parameterValue &sipStrings_phonon[2918]
#define sipNameNr_Phonon__Effect 2933
#define sipName_Phonon__Effect &sipStrings_phonon[2933]
#define sipNameNr_languageChange 2948
#define sipName_languageChange &sipStrings_phonon[2948]
#define sipNameNr_selectedFilter 2963
#define sipName_selectedFilter &sipStrings_phonon[2963]
#define sipNameNr_heightForWidth 2978
#define sipName_heightForWidth &sipStrings_phonon[2978]
#define sipNameNr_setOrientation 2993
#define sipName_setOrientation &sipStrings_phonon[2993]
#define sipNameNr_dragLeaveEvent 3008
#define sipName_dragLeaveEvent &sipStrings_phonon[3008]
#define sipNameNr_dragEnterEvent 3023
#define sipName_dragEnterEvent &sipStrings_phonon[3023]
#define sipNameNr_mouseMoveEvent 3038
#define sipName_mouseMoveEvent &sipStrings_phonon[3038]
#define sipNameNr_maximumVolume 3053
#define sipName_maximumVolume &sipStrings_phonon[3053]
#define sipNameNr_isMuteVisible 3067
#define sipName_isMuteVisible &sipStrings_phonon[3067]
#define sipNameNr_setSaturation 3081
#define sipName_setSaturation &sipStrings_phonon[3081]
#define sipNameNr_setBrightness 3095
#define sipName_setBrightness &sipStrings_phonon[3095]
#define sipNameNr_setFullScreen 3109
#define sipName_setFullScreen &sipStrings_phonon[3109]
#define sipNameNr_isIconVisible 3123
#define sipName_isIconVisible &sipStrings_phonon[3123]
#define sipNameNr_phononVersion 3137
#define sipName_phononVersion &sipStrings_phonon[3137]
#define sipNameNr_VideoCategory 3151
#define sipName_VideoCategory &sipStrings_phonon[3151]
#define sipNameNr_MusicCategory 3165
#define sipName_MusicCategory &sipStrings_phonon[3165]
#define sipNameNr_Phonon__State 3179
#define sipName_Phonon__State &sipStrings_phonon[3179]
#define sipNameNr_GenreMetaData 3193
#define sipName_GenreMetaData &sipStrings_phonon[3193]
#define sipNameNr_TitleMetaData 3207
#define sipName_TitleMetaData &sipStrings_phonon[3207]
#define sipNameNr_AlbumMetaData 3221
#define sipName_AlbumMetaData &sipStrings_phonon[3221]
#define sipNameNr_propertyNames 3235
#define sipName_propertyNames &sipStrings_phonon[3235]
#define sipNameNr_aboutToFinish 3249
#define sipName_aboutToFinish &sipStrings_phonon[3249]
#define sipNameNr_prefinishMark 3263
#define sipName_prefinishMark &sipStrings_phonon[3263]
#define sipNameNr_remainingTime 3277
#define sipName_remainingTime &sipStrings_phonon[3277]
#define sipNameNr_currentSource 3291
#define sipName_currentSource &sipStrings_phonon[3291]
#define sipNameNr_previousTitle 3305
#define sipName_previousTitle &sipStrings_phonon[3305]
#define sipNameNr_volumeChanged 3319
#define sipName_volumeChanged &sipStrings_phonon[3319]
#define sipNameNr_volumeDecibel 3333
#define sipName_volumeDecibel &sipStrings_phonon[3333]
#define sipNameNr_paletteChange 3347
#define sipName_paletteChange &sipStrings_phonon[3347]
#define sipNameNr_enabledChange 3361
#define sipName_enabledChange &sipStrings_phonon[3361]
#define sipNameNr_transformMode 3375
#define sipName_transformMode &sipStrings_phonon[3375]
#define sipNameNr_setSingleStep 3389
#define sipName_setSingleStep &sipStrings_phonon[3389]
#define sipNameNr_dragMoveEvent 3403
#define sipName_dragMoveEvent &sipStrings_phonon[3403]
#define sipNameNr_focusOutEvent 3417
#define sipName_focusOutEvent &sipStrings_phonon[3417]
#define sipNameNr_keyPressEvent 3431
#define sipName_keyPressEvent &sipStrings_phonon[3431]
#define sipNameNr_setAutoDelete 3445
#define sipName_setAutoDelete &sipStrings_phonon[3445]
#define sipNameNr_connectNotify 2374
#define sipName_connectNotify &sipStrings_phonon[2374]
#define sipNameNr_removeColumns 3459
#define sipName_removeColumns &sipStrings_phonon[3459]
#define sipNameNr_insertColumns 3473
#define sipName_insertColumns &sipStrings_phonon[3473]
#define sipNameNr_setHeaderData 3487
#define sipName_setHeaderData &sipStrings_phonon[3487]
#define sipNameNr_VolumeSlider 1456
#define sipName_VolumeSlider &sipStrings_phonon[1456]
#define sipNameNr_setScaleMode 3501
#define sipName_setScaleMode &sipStrings_phonon[3501]
#define sipNameNr_ScaleAndCrop 3514
#define sipName_ScaleAndCrop &sipStrings_phonon[3514]
#define sipNameNr_GameCategory 3527
#define sipName_GameCategory &sipStrings_phonon[3527]
#define sipNameNr_PlayingState 3540
#define sipName_PlayingState &sipStrings_phonon[3540]
#define sipNameNr_StoppedState 3553
#define sipName_StoppedState &sipStrings_phonon[3553]
#define sipNameNr_LoadingState 3566
#define sipName_LoadingState &sipStrings_phonon[3566]
#define sipNameNr_DateMetaData 3579
#define sipName_DateMetaData &sipStrings_phonon[3579]
#define sipNameNr_removeEffect 3592
#define sipName_removeEffect &sipStrings_phonon[3592]
#define sipNameNr_insertEffect 3605
#define sipName_insertEffect &sipStrings_phonon[3605]
#define sipNameNr_Phonon__Path 3618
#define sipName_Phonon__Path &sipStrings_phonon[3618]
#define sipNameNr_createPlayer 3631
#define sipName_createPlayer &sipStrings_phonon[3631]
#define sipNameNr_bufferStatus 3644
#define sipName_bufferStatus &sipStrings_phonon[3644]
#define sipNameNr_titleChanged 3657
#define sipName_titleChanged &sipStrings_phonon[3657]
#define sipNameNr_currentTitle 3670
#define sipName_currentTitle &sipStrings_phonon[3670]
#define sipNameNr_currentAngle 3683
#define sipName_currentAngle &sipStrings_phonon[3683]
#define sipNameNr_EffectWidget 1540
#define sipName_EffectWidget &sipStrings_phonon[1540]
#define sipNameNr_maximumValue 3696
#define sipName_maximumValue &sipStrings_phonon[3696]
#define sipNameNr_minimumValue 3709
#define sipName_minimumValue &sipStrings_phonon[3709]
#define sipNameNr_mutedChanged 3722
#define sipName_mutedChanged &sipStrings_phonon[3722]
#define sipNameNr_outputDevice 3735
#define sipName_outputDevice &sipStrings_phonon[3735]
#define sipNameNr_sourceRegion 3748
#define sipName_sourceRegion &sipStrings_phonon[3748]
#define sipNameNr_targetOffset 3761
#define sipName_targetOffset &sipStrings_phonon[3761]
#define sipNameNr_tickInterval 3774
#define sipName_tickInterval &sipStrings_phonon[3774]
#define sipNameNr_angleChanged 3787
#define sipName_angleChanged &sipStrings_phonon[3787]
#define sipNameNr_boundingRect 3800
#define sipName_boundingRect &sipStrings_phonon[3800]
#define sipNameNr_midLineWidth 3813
#define sipName_midLineWidth &sipStrings_phonon[3813]
#define sipNameNr_setModelData 3826
#define sipName_setModelData &sipStrings_phonon[3826]
#define sipNameNr_focusInEvent 3839
#define sipName_focusInEvent &sipStrings_phonon[3839]
#define sipNameNr_defaultValue 3852
#define sipName_defaultValue &sipStrings_phonon[3852]
#define sipNameNr_canFetchMore 3865
#define sipName_canFetchMore &sipStrings_phonon[3865]
#define sipNameNr_dropMimeData 3878
#define sipName_dropMimeData &sipStrings_phonon[3878]
#define sipNameNr_stateChanged 3891
#define sipName_stateChanged &sipStrings_phonon[3891]
#define sipNameNr_PyQt4_phonon 3904
#define sipName_PyQt4_phonon &sipStrings_phonon[3904]
#define sipNameNr_setContrast 3917
#define sipName_setContrast &sipStrings_phonon[3917]
#define sipNameNr_aspectRatio 3929
#define sipName_aspectRatio &sipStrings_phonon[3929]
#define sipNameNr_AspectRatio 338
#define sipName_AspectRatio &sipStrings_phonon[338]
#define sipNameNr_VideoWidget 1623
#define sipName_VideoWidget &sipStrings_phonon[1623]
#define sipNameNr_videoWidget 3941
#define sipName_videoWidget &sipStrings_phonon[3941]
#define sipNameNr_audioOutput 3953
#define sipName_audioOutput &sipStrings_phonon[3953]
#define sipNameNr_VideoPlayer 1643
#define sipName_VideoPlayer &sipStrings_phonon[1643]
#define sipNameNr_mediaObject 3965
#define sipName_mediaObject &sipStrings_phonon[3965]
#define sipNameNr_NormalError 3977
#define sipName_NormalError &sipStrings_phonon[3977]
#define sipNameNr_PausedState 3989
#define sipName_PausedState &sipStrings_phonon[3989]
#define sipNameNr_MediaSource 1703
#define sipName_MediaSource &sipStrings_phonon[1703]
#define sipNameNr_MediaObject 1723
#define sipName_MediaObject &sipStrings_phonon[1723]
#define sipNameNr_outputPaths 4001
#define sipName_outputPaths &sipStrings_phonon[4001]
#define sipNameNr_IntegerHint 4013
#define sipName_IntegerHint &sipStrings_phonon[4013]
#define sipNameNr_ToggledHint 4025
#define sipName_ToggledHint &sipStrings_phonon[4025]
#define sipNameNr_AudioOutput 847
#define sipName_AudioOutput &sipStrings_phonon[847]
#define sipNameNr_tabletEvent 4037
#define sipName_tabletEvent &sipStrings_phonon[4037]
#define sipNameNr_button2Text 4049
#define sipName_button2Text &sipStrings_phonon[4049]
#define sipNameNr_button1Text 4061
#define sipName_button1Text &sipStrings_phonon[4061]
#define sipNameNr_actionEvent 4073
#define sipName_actionEvent &sipStrings_phonon[4073]
#define sipNameNr_paintEngine 4085
#define sipName_paintEngine &sipStrings_phonon[4085]
#define sipNameNr_description 4097
#define sipName_description &sipStrings_phonon[4097]
#define sipNameNr_hasTracking 4109
#define sipName_hasTracking &sipStrings_phonon[4109]
#define sipNameNr_setTracking 4121
#define sipName_setTracking &sipStrings_phonon[4121]
#define sipNameNr_setPageStep 4133
#define sipName_setPageStep &sipStrings_phonon[4133]
#define sipNameNr_resizeEvent 4145
#define sipName_resizeEvent &sipStrings_phonon[4145]
#define sipNameNr_changeEvent 4157
#define sipName_changeEvent &sipStrings_phonon[4157]
#define sipNameNr_setIconSize 4169
#define sipName_setIconSize &sipStrings_phonon[4169]
#define sipNameNr_customEvent 4181
#define sipName_customEvent &sipStrings_phonon[4181]
#define sipNameNr_eventFilter 4193
#define sipName_eventFilter &sipStrings_phonon[4193]
#define sipNameNr_setItemData 4205
#define sipName_setItemData &sipStrings_phonon[4205]
#define sipNameNr_orientation 4217
#define sipName_orientation &sipStrings_phonon[4217]
#define sipNameNr_hasChildren 4229
#define sipName_hasChildren &sipStrings_phonon[4229]
#define sipNameNr_columnCount 4241
#define sipName_columnCount &sipStrings_phonon[4241]
#define sipNameNr_errorString 4253
#define sipName_errorString &sipStrings_phonon[4253]
#define sipNameNr_currentTime 4265
#define sipName_currentTime &sipStrings_phonon[4265]
#define sipNameNr_brightness 4277
#define sipName_brightness &sipStrings_phonon[4277]
#define sipNameNr_SeekSlider 1863
#define sipName_SeekSlider &sipStrings_phonon[1863]
#define sipNameNr_ErrorState 4288
#define sipName_ErrorState &sipStrings_phonon[4288]
#define sipNameNr_createPath 4299
#define sipName_createPath &sipStrings_phonon[4299]
#define sipNameNr_deviceName 4310
#define sipName_deviceName &sipStrings_phonon[4310]
#define sipNameNr_clearQueue 4321
#define sipName_clearQueue &sipStrings_phonon[4321]
#define sipNameNr_isSeekable 4332
#define sipName_isSeekable &sipStrings_phonon[4332]
#define sipNameNr_inputPaths 4343
#define sipName_inputPaths &sipStrings_phonon[4343]
#define sipNameNr_fontChange 4354
#define sipName_fontChange &sipStrings_phonon[4354]
#define sipNameNr_parameters 4365
#define sipName_parameters &sipStrings_phonon[4365]
#define sipNameNr_enterEvent 4376
#define sipName_enterEvent &sipStrings_phonon[4376]
#define sipNameNr_leaveEvent 4387
#define sipName_leaveEvent &sipStrings_phonon[4387]
#define sipNameNr_saturation 4398
#define sipName_saturation &sipStrings_phonon[4398]
#define sipNameNr_setVisible 4409
#define sipName_setVisible &sipStrings_phonon[4409]
#define sipNameNr_closeEvent 4420
#define sipName_closeEvent &sipStrings_phonon[4420]
#define sipNameNr_singleStep 4431
#define sipName_singleStep &sipStrings_phonon[4431]
#define sipNameNr_wheelEvent 4442
#define sipName_wheelEvent &sipStrings_phonon[4442]
#define sipNameNr_paintEvent 4453
#define sipName_paintEvent &sipStrings_phonon[4453]
#define sipNameNr_fieldWidth 4464
#define sipName_fieldWidth &sipStrings_phonon[4464]
#define sipNameNr_autoDelete 4475
#define sipName_autoDelete &sipStrings_phonon[4475]
#define sipNameNr_childEvent 4486
#define sipName_childEvent &sipStrings_phonon[4486]
#define sipNameNr_timerEvent 4497
#define sipName_timerEvent &sipStrings_phonon[4497]
#define sipNameNr_disconnect 4508
#define sipName_disconnect &sipStrings_phonon[4508]
#define sipNameNr_FatalError 4519
#define sipName_FatalError &sipStrings_phonon[4519]
#define sipNameNr_NoCategory 4530
#define sipName_NoCategory &sipStrings_phonon[4530]
#define sipNameNr_removeRows 4541
#define sipName_removeRows &sipStrings_phonon[4541]
#define sipNameNr_insertRows 4552
#define sipName_insertRows &sipStrings_phonon[4552]
#define sipNameNr_headerData 4563
#define sipName_headerData &sipStrings_phonon[4563]
#define sipNameNr___invert__ 4574
#define sipName___invert__ &sipStrings_phonon[4574]
#define sipNameNr_scaleMode 4585
#define sipName_scaleMode &sipStrings_phonon[4585]
#define sipNameNr_ScaleMode 467
#define sipName_ScaleMode &sipStrings_phonon[467]
#define sipNameNr_isPlaying 4595
#define sipName_isPlaying &sipStrings_phonon[4595]
#define sipNameNr_ErrorType 1995
#define sipName_ErrorType &sipStrings_phonon[1995]
#define sipNameNr_reconnect 4605
#define sipName_reconnect &sipStrings_phonon[4605]
#define sipNameNr_modelData 4615
#define sipName_modelData &sipStrings_phonon[4615]
#define sipNameNr_fromIndex 4625
#define sipName_fromIndex &sipStrings_phonon[4625]
#define sipNameNr_LocalFile 4635
#define sipName_LocalFile &sipStrings_phonon[4635]
#define sipNameNr_totalTime 4645
#define sipName_totalTime &sipStrings_phonon[4645]
#define sipNameNr_errorType 4655
#define sipName_errorType &sipStrings_phonon[4655]
#define sipNameNr_nextTitle 4665
#define sipName_nextTitle &sipStrings_phonon[4665]
#define sipNameNr_setVolume 4675
#define sipName_setVolume &sipStrings_phonon[4675]
#define sipNameNr_MediaNode 2121
#define sipName_MediaNode &sipStrings_phonon[2121]
#define sipNameNr_FitInView 4685
#define sipName_FitInView &sipStrings_phonon[4685]
#define sipNameNr_operation 4695
#define sipName_operation &sipStrings_phonon[4695]
#define sipNameNr_moveEvent 4705
#define sipName_moveEvent &sipStrings_phonon[4705]
#define sipNameNr_lineWidth 4715
#define sipName_lineWidth &sipStrings_phonon[4715]
#define sipNameNr_showEvent 4725
#define sipName_showEvent &sipStrings_phonon[4725]
#define sipNameNr_hideEvent 4735
#define sipName_hideEvent &sipStrings_phonon[4735]
#define sipNameNr_dropEvent 4745
#define sipName_dropEvent &sipStrings_phonon[4745]
#define sipNameNr_directory 4755
#define sipName_directory &sipStrings_phonon[4755]
#define sipNameNr_alignment 4765
#define sipName_alignment &sipStrings_phonon[4765]
#define sipNameNr_precision 4775
#define sipName_precision &sipStrings_phonon[4775]
#define sipNameNr_fetchMore 4785
#define sipName_fetchMore &sipStrings_phonon[4785]
#define sipNameNr_mimeTypes 4795
#define sipName_mimeTypes &sipStrings_phonon[4795]
#define sipNameNr_snapshot 4805
#define sipName_snapshot &sipStrings_phonon[4805]
#define sipNameNr_contrast 4814
#define sipName_contrast &sipStrings_phonon[4814]
#define sipNameNr_isPaused 4823
#define sipName_isPaused &sipStrings_phonon[4823]
#define sipNameNr_MetaData 984
#define sipName_MetaData &sipStrings_phonon[984]
#define sipNameNr_DiscType 2243
#define sipName_DiscType &sipStrings_phonon[2243]
#define sipNameNr_moveDown 4832
#define sipName_moveDown &sipStrings_phonon[4832]
#define sipNameNr_discType 4841
#define sipName_discType &sipStrings_phonon[4841]
#define sipNameNr_setQueue 4850
#define sipName_setQueue &sipStrings_phonon[4850]
#define sipNameNr_metaData 4859
#define sipName_metaData &sipStrings_phonon[4859]
#define sipNameNr_hasVideo 4868
#define sipName_hasVideo &sipStrings_phonon[4868]
#define sipNameNr_Features 242
#define sipName_Features &sipStrings_phonon[242]
#define sipNameNr_Chapters 2068
#define sipName_Chapters &sipStrings_phonon[2068]
#define sipNameNr_Notifier 68
#define sipName_Notifier &sipStrings_phonon[68]
#define sipNameNr_setMuted 4877
#define sipName_setMuted &sipStrings_phonon[4877]
#define sipNameNr_fillRule 4886
#define sipName_fillRule &sipStrings_phonon[4886]
#define sipNameNr_tabArray 4895
#define sipName_tabArray &sipStrings_phonon[4895]
#define sipNameNr_tabStops 4904
#define sipName_tabStops &sipStrings_phonon[4904]
#define sipNameNr_userData 4913
#define sipName_userData &sipStrings_phonon[4913]
#define sipNameNr_pageStep 4922
#define sipName_pageStep &sipStrings_phonon[4922]
#define sipNameNr_sizeHint 4931
#define sipName_sizeHint &sipStrings_phonon[4931]
#define sipNameNr_shortcut 4940
#define sipName_shortcut &sipStrings_phonon[4940]
#define sipNameNr_iconSize 4949
#define sipName_iconSize &sipStrings_phonon[4949]
#define sipNameNr_behavior 4958
#define sipName_behavior &sipStrings_phonon[4958]
#define sipNameNr_position 4967
#define sipName_position &sipStrings_phonon[4967]
#define sipNameNr_fillChar 4976
#define sipName_fillChar &sipStrings_phonon[4976]
#define sipNameNr_property 4985
#define sipName_property &sipStrings_phonon[4985]
#define sipNameNr_category 4994
#define sipName_category &sipStrings_phonon[4994]
#define sipNameNr_Category 1373
#define sipName_Category &sipStrings_phonon[1373]
#define sipNameNr_mimeData 5003
#define sipName_mimeData &sipStrings_phonon[5003]
#define sipNameNr_itemData 5012
#define sipName_itemData &sipStrings_phonon[5012]
#define sipNameNr_rowCount 5021
#define sipName_rowCount &sipStrings_phonon[5021]
#define sipNameNr___hash__ 5030
#define sipName___hash__ &sipStrings_phonon[5030]
#define sipNameNr_fileName 5039
#define sipName_fileName &sipStrings_phonon[5039]
#define sipNameNr_notifier 5048
#define sipName_notifier &sipStrings_phonon[5048]
#define sipNameNr_finished 5057
#define sipName_finished &sipStrings_phonon[5057]
#define sipNameNr___bool__ 5066
#define sipName___bool__ &sipStrings_phonon[5066]
#define sipNameNr___ixor__ 5075
#define sipName___ixor__ &sipStrings_phonon[5075]
#define sipNameNr___iand__ 5084
#define sipName___iand__ &sipStrings_phonon[5084]
#define sipNameNr_effects 5093
#define sipName_effects &sipStrings_phonon[5093]
#define sipNameNr_enqueue 5101
#define sipName_enqueue &sipStrings_phonon[5101]
#define sipNameNr_Feature 375
#define sipName_Feature &sipStrings_phonon[375]
#define sipNameNr_isMuted 5109
#define sipName_isMuted &sipStrings_phonon[5109]
#define sipNameNr_setName 5117
#define sipName_setName &sipStrings_phonon[5117]
#define sipNameNr_exposed 5125
#define sipName_exposed &sipStrings_phonon[5125]
#define sipNameNr_button2 5133
#define sipName_button2 &sipStrings_phonon[5133]
#define sipNameNr_button1 5141
#define sipName_button1 &sipStrings_phonon[5141]
#define sipNameNr_quality 5149
#define sipName_quality &sipStrings_phonon[5149]
#define sipNameNr_devType 5157
#define sipName_devType &sipStrings_phonon[5157]
#define sipNameNr_yMargin 5165
#define sipName_yMargin &sipStrings_phonon[5165]
#define sipNameNr_xMargin 5173
#define sipName_xMargin &sipStrings_phonon[5173]
#define sipNameNr_caption 5181
#define sipName_caption &sipStrings_phonon[5181]
#define sipNameNr_Invalid 5189
#define sipName_Invalid &sipStrings_phonon[5189]
#define sipNameNr_options 5197
#define sipName_options &sipStrings_phonon[5197]
#define sipNameNr_NoError 5205
#define sipName_NoError &sipStrings_phonon[5205]
#define sipNameNr_setData 5213
#define sipName_setData &sipStrings_phonon[5213]
#define sipNameNr_isValid 5221
#define sipName_isValid &sipStrings_phonon[5221]
#define sipNameNr_filters 5229
#define sipName_filters &sipStrings_phonon[5229]
#define sipNameNr___xor__ 5237
#define sipName___xor__ &sipStrings_phonon[5237]
#define sipNameNr___ior__ 5245
#define sipName___ior__ &sipStrings_phonon[5245]
#define sipNameNr___and__ 5253
#define sipName___and__ &sipStrings_phonon[5253]
#define sipNameNr___int__ 5261
#define sipName___int__ &sipStrings_phonon[5261]
#define sipNameNr_setHue 5269
#define sipName_setHue &sipStrings_phonon[5269]
#define sipNameNr_NoDisc 5276
#define sipName_NoDisc &sipStrings_phonon[5276]
#define sipNameNr_moveUp 5283
#define sipName_moveUp &sipStrings_phonon[5283]
#define sipNameNr_Stream 5290
#define sipName_Stream &sipStrings_phonon[5290]
#define sipNameNr_Titles 2034
#define sipName_Titles &sipStrings_phonon[2034]
#define sipNameNr_Angles 2573
#define sipName_Angles &sipStrings_phonon[2573]
#define sipNameNr_Effect 2941
#define sipName_Effect &sipStrings_phonon[2941]
#define sipNameNr_volume 5297
#define sipName_volume &sipStrings_phonon[5297]
#define sipNameNr_Phonon 5304
#define sipName_Phonon &sipStrings_phonon[5304]
#define sipNameNr_yRound 5311
#define sipName_yRound &sipStrings_phonon[5311]
#define sipNameNr_xRound 5318
#define sipName_xRound &sipStrings_phonon[5318]
#define sipNameNr_metric 5325
#define sipName_metric &sipStrings_phonon[5325]
#define sipNameNr_layers 5332
#define sipName_layers &sipStrings_phonon[5332]
#define sipNameNr_sunken 5339
#define sipName_sunken &sipStrings_phonon[5339]
#define sipNameNr_source 5346
#define sipName_source &sipStrings_phonon[5346]
#define sipNameNr_option 5353
#define sipName_option &sipStrings_phonon[5353]
#define sipNameNr_values 5360
#define sipName_values &sipStrings_phonon[5360]
#define sipNameNr_proper 5367
#define sipName_proper &sipStrings_phonon[5367]
#define sipNameNr_value9 5374
#define sipName_value9 &sipStrings_phonon[5374]
#define sipNameNr_value8 5381
#define sipName_value8 &sipStrings_phonon[5381]
#define sipNameNr_value7 5388
#define sipName_value7 &sipStrings_phonon[5388]
#define sipNameNr_value6 5395
#define sipName_value6 &sipStrings_phonon[5395]
#define sipNameNr_value5 5402
#define sipName_value5 &sipStrings_phonon[5402]
#define sipNameNr_value4 5409
#define sipName_value4 &sipStrings_phonon[5409]
#define sipNameNr_value3 5416
#define sipName_value3 &sipStrings_phonon[5416]
#define sipNameNr_value2 5423
#define sipName_value2 &sipStrings_phonon[5423]
#define sipNameNr_value1 5430
#define sipName_value1 &sipStrings_phonon[5430]
#define sipNameNr_value0 5437
#define sipName_value0 &sipStrings_phonon[5437]
#define sipNameNr_symbol 5444
#define sipName_symbol &sipStrings_phonon[5444]
#define sipNameNr_suffix 5451
#define sipName_suffix &sipStrings_phonon[5451]
#define sipNameNr_prefix 5458
#define sipName_prefix &sipStrings_phonon[5458]
#define sipNameNr_format 5465
#define sipName_format &sipStrings_phonon[5465]
#define sipNameNr_before 5472
#define sipName_before &sipStrings_phonon[5472]
#define sipNameNr_revert 5479
#define sipName_revert &sipStrings_phonon[5479]
#define sipNameNr_submit 5486
#define sipName_submit &sipStrings_phonon[5486]
#define sipNameNr_action 5493
#define sipName_action &sipStrings_phonon[5493]
#define sipNameNr_column 5500
#define sipName_column &sipStrings_phonon[5500]
#define sipNameNr_filter 5507
#define sipName_filter &sipStrings_phonon[5507]
#define sipNameNr_parent 5514
#define sipName_parent &sipStrings_phonon[5514]
#define sipNameNr___ne__ 5521
#define sipName___ne__ &sipStrings_phonon[5521]
#define sipNameNr___eq__ 5528
#define sipName___eq__ &sipStrings_phonon[5528]
#define sipNameNr___or__ 5535
#define sipName___or__ &sipStrings_phonon[5535]
#define sipNameNr_Empty 5542
#define sipName_Empty &sipStrings_phonon[5542]
#define sipNameNr_queue 5103
#define sipName_queue &sipStrings_phonon[5103]
#define sipNameNr_Hints 595
#define sipName_Hints &sipStrings_phonon[595]
#define sipNameNr_brush 5548
#define sipName_brush &sipStrings_phonon[5548]
#define sipNameNr_hints 5554
#define sipName_hints &sipStrings_phonon[5554]
#define sipNameNr_clear 5560
#define sipName_clear &sipStrings_phonon[5560]
#define sipNameNr_match 5566
#define sipName_match &sipStrings_phonon[5566]
#define sipNameNr_buddy 5572
#define sipName_buddy &sipStrings_phonon[5572]
#define sipNameNr_index 5578
#define sipName_index &sipStrings_phonon[5578]
#define sipNameNr_flags 5584
#define sipName_flags &sipStrings_phonon[5584]
#define sipNameNr_event 5590
#define sipName_event &sipStrings_phonon[5590]
#define sipNameNr_msecs 5596
#define sipName_msecs &sipStrings_phonon[5596]
#define sipNameNr_pause 5602
#define sipName_pause &sipStrings_phonon[5602]
#define sipNameNr_state 5608
#define sipName_state &sipStrings_phonon[5608]
#define sipNameNr_State 2822
#define sipName_State &sipStrings_phonon[2822]
#define sipNameNr_sink 5614
#define sipName_sink &sipStrings_phonon[5614]
#define sipNameNr_Path 3626
#define sipName_Path &sipStrings_phonon[3626]
#define sipNameNr_Disc 5278
#define sipName_Disc &sipStrings_phonon[5278]
#define sipNameNr_tick 5619
#define sipName_tick &sipStrings_phonon[5619]
#define sipNameNr_Hint 656
#define sipName_Hint &sipStrings_phonon[656]
#define sipNameNr_play 5624
#define sipName_play &sipStrings_phonon[5624]
#define sipNameNr_load 5629
#define sipName_load &sipStrings_phonon[5629]
#define sipNameNr_mode 5634
#define sipName_mode &sipStrings_phonon[5634]
#define sipNameNr_name 5639
#define sipName_name &sipStrings_phonon[5639]
#define sipNameNr_Type 714
#define sipName_Type &sipStrings_phonon[714]
#define sipNameNr_base 5644
#define sipName_base &sipStrings_phonon[5644]
#define sipNameNr_fill 5649
#define sipName_fill &sipStrings_phonon[5649]
#define sipNameNr_from 5654
#define sipName_from &sipStrings_phonon[5654]
#define sipNameNr_span 5659
#define sipName_span &sipStrings_phonon[5659]
#define sipNameNr_sort 5664
#define sipName_sort &sipStrings_phonon[5664]
#define sipNameNr_role 5669
#define sipName_role &sipStrings_phonon[5669]
#define sipNameNr_data 5674
#define sipName_data &sipStrings_phonon[5674]
#define sipNameNr_type 5679
#define sipName_type &sipStrings_phonon[5679]
#define sipNameNr_seek 5684
#define sipName_seek &sipStrings_phonon[5684]
#define sipNameNr_stop 5689
#define sipName_stop &sipStrings_phonon[5689]
#define sipNameNr_Vcd 5694
#define sipName_Vcd &sipStrings_phonon[5694]
#define sipNameNr_Dvd 5698
#define sipName_Dvd &sipStrings_phonon[5698]
#define sipNameNr_pen 5702
#define sipName_pen &sipStrings_phonon[5702]
#define sipNameNr_hue 5706
#define sipName_hue &sipStrings_phonon[5706]
#define sipNameNr_max 5710
#define sipName_max &sipStrings_phonon[5710]
#define sipNameNr_Url 5714
#define sipName_Url &sipStrings_phonon[5714]
#define sipNameNr_url 5718
#define sipName_url &sipStrings_phonon[5718]
#define sipNameNr_min 5722
#define sipName_min &sipStrings_phonon[5722]
#define sipNameNr_end 5726
#define sipName_end &sipStrings_phonon[5726]
#define sipNameNr_pos 5730
#define sipName_pos &sipStrings_phonon[5730]
#define sipNameNr_Cd 5734
#define sipName_Cd &sipStrings_phonon[5734]
#define sipNameNr_sw 5737
#define sipName_sw &sipStrings_phonon[5737]
#define sipNameNr_sy 5740
#define sipName_sy &sipStrings_phonon[5740]
#define sipNameNr_sx 5743
#define sipName_sx &sipStrings_phonon[5743]
#define sipNameNr_sh 3260
#define sipName_sh &sipStrings_phonon[3260]
#define sipNameNr_cs 5599
#define sipName_cs &sipStrings_phonon[5599]

#define sipMalloc                   sipAPI_phonon->api_malloc
#define sipFree                     sipAPI_phonon->api_free
#define sipBuildResult              sipAPI_phonon->api_build_result
#define sipCallMethod               sipAPI_phonon->api_call_method
#define sipCallProcedureMethod      sipAPI_phonon->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_phonon->api_call_error_handler
#define sipParseResultEx            sipAPI_phonon->api_parse_result_ex
#define sipParseResult              sipAPI_phonon->api_parse_result
#define sipParseArgs                sipAPI_phonon->api_parse_args
#define sipParseKwdArgs             sipAPI_phonon->api_parse_kwd_args
#define sipParsePair                sipAPI_phonon->api_parse_pair
#define sipCommonDtor               sipAPI_phonon->api_common_dtor
#define sipConvertFromSequenceIndex sipAPI_phonon->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_phonon->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_phonon->api_convert_to_void_ptr
#define sipAddException             sipAPI_phonon->api_add_exception
#define sipNoFunction               sipAPI_phonon->api_no_function
#define sipNoMethod                 sipAPI_phonon->api_no_method
#define sipAbstractMethod           sipAPI_phonon->api_abstract_method
#define sipBadClass                 sipAPI_phonon->api_bad_class
#define sipBadCatcherResult         sipAPI_phonon->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_phonon->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_phonon->api_bad_operator_arg
#define sipTrace                    sipAPI_phonon->api_trace
#define sipTransferBack             sipAPI_phonon->api_transfer_back
#define sipTransferTo               sipAPI_phonon->api_transfer_to
#define sipTransferBreak            sipAPI_phonon->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_phonon->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_phonon->api_wrapper_type
#define sipWrapperType_Type         sipAPI_phonon->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_phonon->api_voidptr_type
#define sipGetPyObject              sipAPI_phonon->api_get_pyobject
#define sipGetAddress               sipAPI_phonon->api_get_address
#define sipGetMixinAddress          sipAPI_phonon->api_get_mixin_address
#define sipGetCppPtr                sipAPI_phonon->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_phonon->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_phonon->api_is_py_method
#define sipCallHook                 sipAPI_phonon->api_call_hook
#define sipEndThread                sipAPI_phonon->api_end_thread
#define sipConnectRx                sipAPI_phonon->api_connect_rx
#define sipDisconnectRx             sipAPI_phonon->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_phonon->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_phonon->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_phonon->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_phonon->api_add_type_instance
#define sipFreeSipslot              sipAPI_phonon->api_free_sipslot
#define sipSameSlot                 sipAPI_phonon->api_same_slot
#define sipPySlotExtend             sipAPI_phonon->api_pyslot_extend
#define sipConvertRx                sipAPI_phonon->api_convert_rx
#define sipAddDelayedDtor           sipAPI_phonon->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_phonon->api_can_convert_to_type
#define sipConvertToType            sipAPI_phonon->api_convert_to_type
#define sipForceConvertToType       sipAPI_phonon->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_phonon->api_can_convert_to_enum
#define sipReleaseType              sipAPI_phonon->api_release_type
#define sipConvertFromType          sipAPI_phonon->api_convert_from_type
#define sipConvertFromNewType       sipAPI_phonon->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_phonon->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_phonon->api_convert_from_enum
#define sipGetState                 sipAPI_phonon->api_get_state
#define sipLong_AsUnsignedLong      sipAPI_phonon->api_long_as_unsigned_long
#define sipExportSymbol             sipAPI_phonon->api_export_symbol
#define sipImportSymbol             sipAPI_phonon->api_import_symbol
#define sipFindType                 sipAPI_phonon->api_find_type
#define sipFindNamedEnum            sipAPI_phonon->api_find_named_enum
#define sipBytes_AsChar             sipAPI_phonon->api_bytes_as_char
#define sipBytes_AsString           sipAPI_phonon->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_phonon->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_phonon->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_phonon->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_phonon->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_phonon->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_phonon->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_phonon->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_phonon->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_phonon->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_phonon->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_phonon->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_phonon->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_phonon->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_phonon->api_save_slot
#define sipClearAnySlotReference    sipAPI_phonon->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_phonon->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->type->td_cname)
#define sipDeprecated               sipAPI_phonon->api_deprecated
#define sipGetReference             sipAPI_phonon->api_get_reference
#define sipKeepReference            sipAPI_phonon->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_phonon->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_phonon->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_phonon->api_type_from_py_type_object
#define sipTypeScope                sipAPI_phonon->api_type_scope
#define sipResolveTypedef           sipAPI_phonon->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_phonon->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_phonon->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_phonon->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_phonon->api_enable_autoconversion
#define sipInitMixin                sipAPI_phonon->api_init_mixin
#define sipExportModule             sipAPI_phonon->api_export_module
#define sipInitModule               sipAPI_phonon->api_init_module
#define sipGetInterpreter           sipAPI_phonon->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_phonon->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_phonon->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_phonon->api_get_type_user_data
#define sipPyTypeDict               sipAPI_phonon->api_py_type_dict
#define sipPyTypeName               sipAPI_phonon->api_py_type_name
#define sipGetCFunction             sipAPI_phonon->api_get_c_function
#define sipGetMethod                sipAPI_phonon->api_get_method
#define sipFromMethod               sipAPI_phonon->api_from_method
#define sipGetDate                  sipAPI_phonon->api_get_date
#define sipFromDate                 sipAPI_phonon->api_from_date
#define sipGetDateTime              sipAPI_phonon->api_get_datetime
#define sipFromDateTime             sipAPI_phonon->api_from_datetime
#define sipGetTime                  sipAPI_phonon->api_get_time
#define sipFromTime                 sipAPI_phonon->api_from_time
#define sipIsUserType               sipAPI_phonon->api_is_user_type
#define sipGetFrame                 sipAPI_phonon->api_get_frame
#define sipCheckPluginForType       sipAPI_phonon->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_phonon->api_unicode_new
#define sipUnicodeWrite             sipAPI_phonon->api_unicode_write
#define sipUnicodeData              sipAPI_phonon->api_unicode_data
#define sipGetBufferInfo            sipAPI_phonon->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_phonon->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_phonon->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_phonon->api_is_derived_class
#define sipGetUserObject            sipAPI_phonon->api_get_user_object
#define sipSetUserObject            sipAPI_phonon->api_set_user_object

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_phonon->api_map_string_to_class
#define sipMapIntToClass            sipAPI_phonon->api_map_int_to_class
#define sipFindClass                sipAPI_phonon->api_find_class
#define sipFindMappedType           sipAPI_phonon->api_find_mapped_type
#define sipConvertToArray           sipAPI_phonon->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_phonon->api_convert_to_typed_array
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_phonon->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->type)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->type, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->type, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->type, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->type, (t))

/* The strings used by this module. */
extern const char sipStrings_phonon[];

#define sipType_Phonon sipExportedTypes_phonon[0]
#define sipClass_Phonon sipExportedTypes_phonon[0]->u.td_wrapper_type

#define sipType_Phonon_ErrorType sipExportedTypes_phonon[19]
#define sipEnum_Phonon_ErrorType sipExportedTypes_phonon[19]->u.td_py_type

#define sipType_Phonon_Category sipExportedTypes_phonon[10]
#define sipEnum_Phonon_Category sipExportedTypes_phonon[10]->u.td_py_type

#define sipType_Phonon_State sipExportedTypes_phonon[30]
#define sipEnum_Phonon_State sipExportedTypes_phonon[30]->u.td_py_type

#define sipType_Phonon_MetaData sipExportedTypes_phonon[27]
#define sipEnum_Phonon_MetaData sipExportedTypes_phonon[27]->u.td_py_type

#define sipType_Phonon_DiscType sipExportedTypes_phonon[11]
#define sipEnum_Phonon_DiscType sipExportedTypes_phonon[11]->u.td_py_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon;

#define sipType_Phonon_MediaNode sipExportedTypes_phonon[23]
#define sipClass_Phonon_MediaNode sipExportedTypes_phonon[23]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_MediaNode;

#define sipType_Phonon_AbstractAudioOutput sipExportedTypes_phonon[1]
#define sipClass_Phonon_AbstractAudioOutput sipExportedTypes_phonon[1]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_AbstractAudioOutput;

#define sipType_Phonon_AbstractVideoOutput sipExportedTypes_phonon[2]
#define sipClass_Phonon_AbstractVideoOutput sipExportedTypes_phonon[2]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_AbstractVideoOutput;

#define sipType_Phonon_AudioOutput sipExportedTypes_phonon[5]
#define sipClass_Phonon_AudioOutput sipExportedTypes_phonon[5]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_AudioOutput;

#define sipType_Phonon_BackendCapabilities sipExportedTypes_phonon[8]
#define sipClass_Phonon_BackendCapabilities sipExportedTypes_phonon[8]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_BackendCapabilities;

#define sipType_Phonon_BackendCapabilities_Notifier sipExportedTypes_phonon[9]
#define sipClass_Phonon_BackendCapabilities_Notifier sipExportedTypes_phonon[9]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_BackendCapabilities_Notifier;

#define sipType_Phonon_Effect sipExportedTypes_phonon[12]
#define sipClass_Phonon_Effect sipExportedTypes_phonon[12]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_Effect;

#define sipType_Phonon_EffectParameter sipExportedTypes_phonon[15]
#define sipClass_Phonon_EffectParameter sipExportedTypes_phonon[15]->u.td_wrapper_type

#define sipType_Phonon_EffectParameter_Hint sipExportedTypes_phonon[16]
#define sipEnum_Phonon_EffectParameter_Hint sipExportedTypes_phonon[16]->u.td_py_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_EffectParameter;

#define sipType_Phonon_EffectParameter_Hints sipExportedTypes_phonon[17]
#define sipClass_Phonon_EffectParameter_Hints sipExportedTypes_phonon[17]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_EffectParameter_Hints;

#define sipType_Phonon_EffectWidget sipExportedTypes_phonon[18]
#define sipClass_Phonon_EffectWidget sipExportedTypes_phonon[18]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_EffectWidget;

#define sipType_Phonon_MediaController sipExportedTypes_phonon[20]
#define sipClass_Phonon_MediaController sipExportedTypes_phonon[20]->u.td_wrapper_type

#define sipType_Phonon_MediaController_Feature sipExportedTypes_phonon[21]
#define sipEnum_Phonon_MediaController_Feature sipExportedTypes_phonon[21]->u.td_py_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_MediaController;

#define sipType_Phonon_MediaController_Features sipExportedTypes_phonon[22]
#define sipClass_Phonon_MediaController_Features sipExportedTypes_phonon[22]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_MediaController_Features;

#define sipType_Phonon_MediaObject sipExportedTypes_phonon[24]
#define sipClass_Phonon_MediaObject sipExportedTypes_phonon[24]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_MediaObject;

#define sipType_Phonon_MediaSource sipExportedTypes_phonon[25]
#define sipClass_Phonon_MediaSource sipExportedTypes_phonon[25]->u.td_wrapper_type

#define sipType_Phonon_MediaSource_Type sipExportedTypes_phonon[26]
#define sipEnum_Phonon_MediaSource_Type sipExportedTypes_phonon[26]->u.td_py_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_MediaSource;

#define sipType_Phonon_AudioOutputDevice sipExportedTypes_phonon[6]
#define sipClass_Phonon_AudioOutputDevice sipExportedTypes_phonon[6]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_AudioOutputDevice;

#define sipType_Phonon_EffectDescription sipExportedTypes_phonon[13]
#define sipClass_Phonon_EffectDescription sipExportedTypes_phonon[13]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_EffectDescription;

#define sipType_Phonon_SubtitleDescription sipExportedTypes_phonon[31]
#define sipClass_Phonon_SubtitleDescription sipExportedTypes_phonon[31]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_SubtitleDescription;

#define sipType_Phonon_AudioChannelDescription sipExportedTypes_phonon[4]
#define sipClass_Phonon_AudioChannelDescription sipExportedTypes_phonon[4]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_AudioChannelDescription;

#define sipType_Phonon_AudioCaptureDevice sipExportedTypes_phonon[3]
#define sipClass_Phonon_AudioCaptureDevice sipExportedTypes_phonon[3]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_AudioCaptureDevice;

#define sipType_Phonon_AudioOutputDeviceModel sipExportedTypes_phonon[7]
#define sipClass_Phonon_AudioOutputDeviceModel sipExportedTypes_phonon[7]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_AudioOutputDeviceModel;

#define sipType_Phonon_EffectDescriptionModel sipExportedTypes_phonon[14]
#define sipClass_Phonon_EffectDescriptionModel sipExportedTypes_phonon[14]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_EffectDescriptionModel;

#define sipType_Phonon_Path sipExportedTypes_phonon[28]
#define sipClass_Phonon_Path sipExportedTypes_phonon[28]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_Path;

#define sipType_Phonon_SeekSlider sipExportedTypes_phonon[29]
#define sipClass_Phonon_SeekSlider sipExportedTypes_phonon[29]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_SeekSlider;

#define sipType_Phonon_VideoPlayer sipExportedTypes_phonon[32]
#define sipClass_Phonon_VideoPlayer sipExportedTypes_phonon[32]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_VideoPlayer;

#define sipType_Phonon_VideoWidget sipExportedTypes_phonon[33]
#define sipClass_Phonon_VideoWidget sipExportedTypes_phonon[33]->u.td_wrapper_type

#define sipType_Phonon_VideoWidget_ScaleMode sipExportedTypes_phonon[35]
#define sipEnum_Phonon_VideoWidget_ScaleMode sipExportedTypes_phonon[35]->u.td_py_type

#define sipType_Phonon_VideoWidget_AspectRatio sipExportedTypes_phonon[34]
#define sipEnum_Phonon_VideoWidget_AspectRatio sipExportedTypes_phonon[34]->u.td_py_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_VideoWidget;

#define sipType_Phonon_VolumeSlider sipExportedTypes_phonon[36]
#define sipClass_Phonon_VolumeSlider sipExportedTypes_phonon[36]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_phonon_Phonon_VolumeSlider;

#define sipType_QList_0101Phonon_Effect sipExportedTypes_phonon[46]

extern sipMappedTypeDef sipTypeDef_phonon_QList_0101Phonon_Effect;

#define sipType_QHash_0100QByteArray_0100QVariant sipExportedTypes_phonon[37]

extern sipMappedTypeDef sipTypeDef_phonon_QHash_0100QByteArray_0100QVariant;

#define sipType_QList_0100Phonon_MediaSource sipExportedTypes_phonon[43]

extern sipMappedTypeDef sipTypeDef_phonon_QList_0100Phonon_MediaSource;

#define sipType_QMultiMap_0100QString_0100QString sipExportedTypes_phonon[47]

extern sipMappedTypeDef sipTypeDef_phonon_QMultiMap_0100QString_0100QString;

#define sipType_QList_0100Phonon_SubtitleDescription sipExportedTypes_phonon[45]

extern sipMappedTypeDef sipTypeDef_phonon_QList_0100Phonon_SubtitleDescription;

#define sipType_QList_0100Phonon_AudioChannelDescription sipExportedTypes_phonon[39]

extern sipMappedTypeDef sipTypeDef_phonon_QList_0100Phonon_AudioChannelDescription;

#define sipType_QList_0100Phonon_EffectParameter sipExportedTypes_phonon[42]

extern sipMappedTypeDef sipTypeDef_phonon_QList_0100Phonon_EffectParameter;

#define sipType_QList_0100Phonon_AudioCaptureDevice sipExportedTypes_phonon[38]

extern sipMappedTypeDef sipTypeDef_phonon_QList_0100Phonon_AudioCaptureDevice;

#define sipType_QList_0100Phonon_EffectDescription sipExportedTypes_phonon[41]

extern sipMappedTypeDef sipTypeDef_phonon_QList_0100Phonon_EffectDescription;

#define sipType_QList_0100Phonon_AudioOutputDevice sipExportedTypes_phonon[40]

extern sipMappedTypeDef sipTypeDef_phonon_QList_0100Phonon_AudioOutputDevice;

#define sipType_QList_0100Phonon_Path sipExportedTypes_phonon[44]

extern sipMappedTypeDef sipTypeDef_phonon_QList_0100Phonon_Path;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_phonon;
extern sipExportedModuleDef sipModuleAPI_phonon;
extern sipTypeDef *sipExportedTypes_phonon[];

#define sipType_Qt_DropAction sipImportedTypes_phonon_QtCore[22].it_td
#define sipEnum_Qt_DropAction sipImportedTypes_phonon_QtCore[22].it_td->u.td_py_type

#define sipType_Qt_InputMethodQuery sipImportedTypes_phonon_QtCore[24].it_td
#define sipEnum_Qt_InputMethodQuery sipImportedTypes_phonon_QtCore[24].it_td->u.td_py_type

#define sipType_Qt_SortOrder sipImportedTypes_phonon_QtCore[28].it_td
#define sipEnum_Qt_SortOrder sipImportedTypes_phonon_QtCore[28].it_td->u.td_py_type

#define sipType_Qt_Orientation sipImportedTypes_phonon_QtCore[27].it_td
#define sipEnum_Qt_Orientation sipImportedTypes_phonon_QtCore[27].it_td->u.td_py_type

#define sipType_Qt_DropActions sipImportedTypes_phonon_QtCore[23].it_td
#define sipClass_Qt_DropActions sipImportedTypes_phonon_QtCore[23].it_td->u.td_wrapper_type

#define sipType_Qt_ItemFlags sipImportedTypes_phonon_QtCore[25].it_td
#define sipClass_Qt_ItemFlags sipImportedTypes_phonon_QtCore[25].it_td->u.td_wrapper_type

#define sipType_Qt_MatchFlags sipImportedTypes_phonon_QtCore[26].it_td
#define sipClass_Qt_MatchFlags sipImportedTypes_phonon_QtCore[26].it_td->u.td_wrapper_type

#define sipType_QObject sipImportedTypes_phonon_QtCore[14].it_td
#define sipClass_QObject sipImportedTypes_phonon_QtCore[14].it_td->u.td_wrapper_type

#define sipType_QModelIndex sipImportedTypes_phonon_QtCore[13].it_td
#define sipClass_QModelIndex sipImportedTypes_phonon_QtCore[13].it_td->u.td_wrapper_type

#define sipType_QAbstractItemModel sipImportedTypes_phonon_QtCore[0].it_td
#define sipClass_QAbstractItemModel sipImportedTypes_phonon_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QAbstractListModel sipImportedTypes_phonon_QtCore[1].it_td
#define sipClass_QAbstractListModel sipImportedTypes_phonon_QtCore[1].it_td->u.td_wrapper_type

#define sipType_QIODevice sipImportedTypes_phonon_QtCore[5].it_td
#define sipClass_QIODevice sipImportedTypes_phonon_QtCore[5].it_td->u.td_wrapper_type

#define sipType_QByteArray sipImportedTypes_phonon_QtCore[2].it_td
#define sipClass_QByteArray sipImportedTypes_phonon_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QEvent sipImportedTypes_phonon_QtCore[4].it_td
#define sipClass_QEvent sipImportedTypes_phonon_QtCore[4].it_td->u.td_wrapper_type

#define sipType_QTimerEvent sipImportedTypes_phonon_QtCore[18].it_td
#define sipClass_QTimerEvent sipImportedTypes_phonon_QtCore[18].it_td->u.td_wrapper_type

#define sipType_QChildEvent sipImportedTypes_phonon_QtCore[3].it_td
#define sipClass_QChildEvent sipImportedTypes_phonon_QtCore[3].it_td->u.td_wrapper_type

#define sipType_QMimeData sipImportedTypes_phonon_QtCore[12].it_td
#define sipClass_QMimeData sipImportedTypes_phonon_QtCore[12].it_td->u.td_wrapper_type

#define sipType_QSize sipImportedTypes_phonon_QtCore[15].it_td
#define sipClass_QSize sipImportedTypes_phonon_QtCore[15].it_td->u.td_wrapper_type

#define sipType_QUrl sipImportedTypes_phonon_QtCore[19].it_td
#define sipClass_QUrl sipImportedTypes_phonon_QtCore[19].it_td->u.td_wrapper_type

#define sipType_QVariant sipImportedTypes_phonon_QtCore[20].it_td
#define sipClass_QVariant sipImportedTypes_phonon_QtCore[20].it_td->u.td_wrapper_type

#define sipType_QVariant_Type sipImportedTypes_phonon_QtCore[21].it_td
#define sipEnum_QVariant_Type sipImportedTypes_phonon_QtCore[21].it_td->u.td_py_type

#define sipType_QList_0100QUrl sipImportedTypes_phonon_QtCore[8].it_td

#define sipType_QMap_1800_0100QVariant sipImportedTypes_phonon_QtCore[11].it_td

#define sipType_QList_0100QByteArray sipImportedTypes_phonon_QtCore[6].it_td

#define sipType_QList_0100QVariant sipImportedTypes_phonon_QtCore[9].it_td

#define sipType_QList_0100QModelIndex sipImportedTypes_phonon_QtCore[7].it_td

#define sipType_QStringList sipImportedTypes_phonon_QtCore[17].it_td

#define sipType_QString sipImportedTypes_phonon_QtCore[16].it_td

#define sipType_QList_1800 sipImportedTypes_phonon_QtCore[10].it_td
extern sipImportedTypeDef sipImportedTypes_phonon_QtCore[];

#define sipType_QPaintDevice sipImportedTypes_phonon_QtGui[15].it_td
#define sipClass_QPaintDevice sipImportedTypes_phonon_QtGui[15].it_td->u.td_wrapper_type

#define sipType_QPaintDevice_PaintDeviceMetric sipImportedTypes_phonon_QtGui[16].it_td
#define sipEnum_QPaintDevice_PaintDeviceMetric sipImportedTypes_phonon_QtGui[16].it_td->u.td_py_type

#define sipType_QWidget sipImportedTypes_phonon_QtGui[24].it_td
#define sipClass_QWidget sipImportedTypes_phonon_QtGui[24].it_td->u.td_wrapper_type

#define sipType_QMouseEvent sipImportedTypes_phonon_QtGui[13].it_td
#define sipClass_QMouseEvent sipImportedTypes_phonon_QtGui[13].it_td->u.td_wrapper_type

#define sipType_QWheelEvent sipImportedTypes_phonon_QtGui[23].it_td
#define sipClass_QWheelEvent sipImportedTypes_phonon_QtGui[23].it_td->u.td_wrapper_type

#define sipType_QTabletEvent sipImportedTypes_phonon_QtGui[22].it_td
#define sipClass_QTabletEvent sipImportedTypes_phonon_QtGui[22].it_td->u.td_wrapper_type

#define sipType_QKeyEvent sipImportedTypes_phonon_QtGui[12].it_td
#define sipClass_QKeyEvent sipImportedTypes_phonon_QtGui[12].it_td->u.td_wrapper_type

#define sipType_QFocusEvent sipImportedTypes_phonon_QtGui[7].it_td
#define sipClass_QFocusEvent sipImportedTypes_phonon_QtGui[7].it_td->u.td_wrapper_type

#define sipType_QPaintEvent sipImportedTypes_phonon_QtGui[18].it_td
#define sipClass_QPaintEvent sipImportedTypes_phonon_QtGui[18].it_td->u.td_wrapper_type

#define sipType_QMoveEvent sipImportedTypes_phonon_QtGui[14].it_td
#define sipClass_QMoveEvent sipImportedTypes_phonon_QtGui[14].it_td->u.td_wrapper_type

#define sipType_QResizeEvent sipImportedTypes_phonon_QtGui[20].it_td
#define sipClass_QResizeEvent sipImportedTypes_phonon_QtGui[20].it_td->u.td_wrapper_type

#define sipType_QCloseEvent sipImportedTypes_phonon_QtGui[1].it_td
#define sipClass_QCloseEvent sipImportedTypes_phonon_QtGui[1].it_td->u.td_wrapper_type

#define sipType_QShowEvent sipImportedTypes_phonon_QtGui[21].it_td
#define sipClass_QShowEvent sipImportedTypes_phonon_QtGui[21].it_td->u.td_wrapper_type

#define sipType_QHideEvent sipImportedTypes_phonon_QtGui[9].it_td
#define sipClass_QHideEvent sipImportedTypes_phonon_QtGui[9].it_td->u.td_wrapper_type

#define sipType_QContextMenuEvent sipImportedTypes_phonon_QtGui[2].it_td
#define sipClass_QContextMenuEvent sipImportedTypes_phonon_QtGui[2].it_td->u.td_wrapper_type

#define sipType_QInputMethodEvent sipImportedTypes_phonon_QtGui[11].it_td
#define sipClass_QInputMethodEvent sipImportedTypes_phonon_QtGui[11].it_td->u.td_wrapper_type

#define sipType_QDropEvent sipImportedTypes_phonon_QtGui[6].it_td
#define sipClass_QDropEvent sipImportedTypes_phonon_QtGui[6].it_td->u.td_wrapper_type

#define sipType_QDragMoveEvent sipImportedTypes_phonon_QtGui[5].it_td
#define sipClass_QDragMoveEvent sipImportedTypes_phonon_QtGui[5].it_td->u.td_wrapper_type

#define sipType_QDragEnterEvent sipImportedTypes_phonon_QtGui[3].it_td
#define sipClass_QDragEnterEvent sipImportedTypes_phonon_QtGui[3].it_td->u.td_wrapper_type

#define sipType_QDragLeaveEvent sipImportedTypes_phonon_QtGui[4].it_td
#define sipClass_QDragLeaveEvent sipImportedTypes_phonon_QtGui[4].it_td->u.td_wrapper_type

#define sipType_QActionEvent sipImportedTypes_phonon_QtGui[0].it_td
#define sipClass_QActionEvent sipImportedTypes_phonon_QtGui[0].it_td->u.td_wrapper_type

#define sipType_QFont sipImportedTypes_phonon_QtGui[8].it_td
#define sipClass_QFont sipImportedTypes_phonon_QtGui[8].it_td->u.td_wrapper_type

#define sipType_QImage sipImportedTypes_phonon_QtGui[10].it_td
#define sipClass_QImage sipImportedTypes_phonon_QtGui[10].it_td->u.td_wrapper_type

#define sipType_QPaintEngine sipImportedTypes_phonon_QtGui[17].it_td
#define sipClass_QPaintEngine sipImportedTypes_phonon_QtGui[17].it_td->u.td_wrapper_type

#define sipType_QPalette sipImportedTypes_phonon_QtGui[19].it_td
#define sipClass_QPalette sipImportedTypes_phonon_QtGui[19].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_phonon_QtGui[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_phonon_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_phonon_qt_metacall;

typedef int (*sip_qt_metacast_func)(sipSimpleWrapper *, sipTypeDef *, const char *);
extern sip_qt_metacast_func sip_phonon_qt_metacast;

#endif
