/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19
 *
 * Copyright (c) 2016 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt4.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIphonon.h"

#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/abstractaudiooutput.sip"
#include <abstractaudiooutput.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/abstractvideooutput.sip"
#include <abstractvideooutput.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/audiooutput.sip"
#include <audiooutput.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/backendcapabilities.sip"
#include <backendcapabilities.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/effect.sip"
#include <effect.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/effectparameter.sip"
#include <effectparameter.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/effectwidget.sip"
#include <effectwidget.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/mediacontroller.sip"
#include <mediacontroller.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/medianode.sip"
#include <medianode.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/mediaobject.sip"
#include <mediaobject.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/mediasource.sip"
#include <mediasource.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/objectdescription.sip"
#include <objectdescription.h>
#line 39 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/objectdescription.sip"
#include <objectdescription.h>
#line 53 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/phonon/sipphononPhononSubtitleDescription.cpp"

#line 28 "sip/QtCore/qhash.sip"
#include <qhash.h>
#line 57 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/phonon/sipphononPhononSubtitleDescription.cpp"
#line 32 "sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 60 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/phonon/sipphononPhononSubtitleDescription.cpp"
#line 26 "sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 63 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/phonon/sipphononPhononSubtitleDescription.cpp"
#line 28 "sip/QtCore/qlist.sip"
#include <qlist.h>
#line 66 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/phonon/sipphononPhononSubtitleDescription.cpp"
#line 265 "sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 69 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/phonon/sipphononPhononSubtitleDescription.cpp"
#line 27 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 72 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/phonon/sipphononPhononSubtitleDescription.cpp"


PyDoc_STRVAR(doc_Phonon_SubtitleDescription_description, "description(self) -> str");

extern "C" {static PyObject *meth_Phonon_SubtitleDescription_description(PyObject *, PyObject *);}
static PyObject *meth_Phonon_SubtitleDescription_description(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::Phonon::SubtitleDescription *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_Phonon_SubtitleDescription, &sipCpp))
        {
             ::QString*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new  ::QString(sipCpp->description());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SubtitleDescription, sipName_description, doc_Phonon_SubtitleDescription_description);

    return NULL;
}


PyDoc_STRVAR(doc_Phonon_SubtitleDescription_index, "index(self) -> int");

extern "C" {static PyObject *meth_Phonon_SubtitleDescription_index(PyObject *, PyObject *);}
static PyObject *meth_Phonon_SubtitleDescription_index(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::Phonon::SubtitleDescription *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_Phonon_SubtitleDescription, &sipCpp))
        {
            int sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->index();
            Py_END_ALLOW_THREADS

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SubtitleDescription, sipName_index, doc_Phonon_SubtitleDescription_index);

    return NULL;
}


PyDoc_STRVAR(doc_Phonon_SubtitleDescription_isValid, "isValid(self) -> bool");

extern "C" {static PyObject *meth_Phonon_SubtitleDescription_isValid(PyObject *, PyObject *);}
static PyObject *meth_Phonon_SubtitleDescription_isValid(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::Phonon::SubtitleDescription *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_Phonon_SubtitleDescription, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->isValid();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SubtitleDescription, sipName_isValid, doc_Phonon_SubtitleDescription_isValid);

    return NULL;
}


PyDoc_STRVAR(doc_Phonon_SubtitleDescription_name, "name(self) -> str");

extern "C" {static PyObject *meth_Phonon_SubtitleDescription_name(PyObject *, PyObject *);}
static PyObject *meth_Phonon_SubtitleDescription_name(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::Phonon::SubtitleDescription *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_Phonon_SubtitleDescription, &sipCpp))
        {
             ::QString*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new  ::QString(sipCpp->name());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SubtitleDescription, sipName_name, doc_Phonon_SubtitleDescription_name);

    return NULL;
}


PyDoc_STRVAR(doc_Phonon_SubtitleDescription_property, "property(self, str) -> Any");

extern "C" {static PyObject *meth_Phonon_SubtitleDescription_property(PyObject *, PyObject *);}
static PyObject *meth_Phonon_SubtitleDescription_property(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char* a0;
        const  ::Phonon::SubtitleDescription *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bs", &sipSelf, sipType_Phonon_SubtitleDescription, &sipCpp, &a0))
        {
             ::QVariant*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new  ::QVariant(sipCpp->property(a0));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QVariant,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SubtitleDescription, sipName_property, doc_Phonon_SubtitleDescription_property);

    return NULL;
}


PyDoc_STRVAR(doc_Phonon_SubtitleDescription_propertyNames, "propertyNames(self) -> List[QByteArray]");

extern "C" {static PyObject *meth_Phonon_SubtitleDescription_propertyNames(PyObject *, PyObject *);}
static PyObject *meth_Phonon_SubtitleDescription_propertyNames(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::Phonon::SubtitleDescription *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_Phonon_SubtitleDescription, &sipCpp))
        {
            QList< ::QByteArray>*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QList< ::QByteArray>(sipCpp->propertyNames());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QList_0100QByteArray,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SubtitleDescription, sipName_propertyNames, doc_Phonon_SubtitleDescription_propertyNames);

    return NULL;
}


PyDoc_STRVAR(doc_Phonon_SubtitleDescription_fromIndex, "fromIndex(int) -> Phonon.SubtitleDescription");

extern "C" {static PyObject *meth_Phonon_SubtitleDescription_fromIndex(PyObject *, PyObject *);}
static PyObject *meth_Phonon_SubtitleDescription_fromIndex(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArgs, "i", &a0))
        {
             ::Phonon::SubtitleDescription*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new  ::Phonon::SubtitleDescription( ::Phonon::SubtitleDescription::fromIndex(a0));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_Phonon_SubtitleDescription,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SubtitleDescription, sipName_fromIndex, doc_Phonon_SubtitleDescription_fromIndex);

    return NULL;
}


extern "C" {static PyObject *slot_Phonon_SubtitleDescription___eq__(PyObject *,PyObject *);}
static PyObject *slot_Phonon_SubtitleDescription___eq__(PyObject *sipSelf,PyObject *sipArg)
{
     ::Phonon::SubtitleDescription *sipCpp = reinterpret_cast< ::Phonon::SubtitleDescription *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_Phonon_SubtitleDescription));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const  ::Phonon::SubtitleDescription* a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J9", sipType_Phonon_SubtitleDescription, &a0))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp-> ::Phonon::SubtitleDescription::operator==(*a0);
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_phonon, eq_slot, sipType_Phonon_SubtitleDescription, sipSelf, sipArg);
}


extern "C" {static PyObject *slot_Phonon_SubtitleDescription___ne__(PyObject *,PyObject *);}
static PyObject *slot_Phonon_SubtitleDescription___ne__(PyObject *sipSelf,PyObject *sipArg)
{
     ::Phonon::SubtitleDescription *sipCpp = reinterpret_cast< ::Phonon::SubtitleDescription *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_Phonon_SubtitleDescription));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const  ::Phonon::SubtitleDescription* a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J9", sipType_Phonon_SubtitleDescription, &a0))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp-> ::Phonon::SubtitleDescription::operator!=(*a0);
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_phonon, ne_slot, sipType_Phonon_SubtitleDescription, sipSelf, sipArg);
}


/* Call the instance's destructor. */
extern "C" {static void release_Phonon_SubtitleDescription(void *, int);}
static void release_Phonon_SubtitleDescription(void *sipCppV, int)
{
    Py_BEGIN_ALLOW_THREADS

    delete reinterpret_cast< ::Phonon::SubtitleDescription *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void assign_Phonon_SubtitleDescription(void *, SIP_SSIZE_T, const void *);}
static void assign_Phonon_SubtitleDescription(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast< ::Phonon::SubtitleDescription *>(sipDst)[sipDstIdx] = *reinterpret_cast<const  ::Phonon::SubtitleDescription *>(sipSrc);
}


extern "C" {static void *array_Phonon_SubtitleDescription(SIP_SSIZE_T);}
static void *array_Phonon_SubtitleDescription(SIP_SSIZE_T sipNrElem)
{
    return new  ::Phonon::SubtitleDescription[sipNrElem];
}


extern "C" {static void *copy_Phonon_SubtitleDescription(const void *, SIP_SSIZE_T);}
static void *copy_Phonon_SubtitleDescription(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new  ::Phonon::SubtitleDescription(reinterpret_cast<const  ::Phonon::SubtitleDescription *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_Phonon_SubtitleDescription(sipSimpleWrapper *);}
static void dealloc_Phonon_SubtitleDescription(sipSimpleWrapper *sipSelf)
{
    if (sipIsOwnedByPython(sipSelf))
    {
        release_Phonon_SubtitleDescription(sipGetAddress(sipSelf), 0);
    }
}


extern "C" {static void *init_type_Phonon_SubtitleDescription(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_Phonon_SubtitleDescription(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
     ::Phonon::SubtitleDescription *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new  ::Phonon::SubtitleDescription();
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        int a0;
        const QHash< ::QByteArray, ::QVariant>* a1;
        int a1State = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "iJ1", &a0, sipType_QHash_0100QByteArray_0100QVariant,&a1, &a1State))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new  ::Phonon::SubtitleDescription(a0,*a1);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QHash< ::QByteArray, ::QVariant> *>(a1),sipType_QHash_0100QByteArray_0100QVariant,a1State);

            return sipCpp;
        }
    }

    {
        const  ::Phonon::SubtitleDescription* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_Phonon_SubtitleDescription, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new  ::Phonon::SubtitleDescription(*a0);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's Python slots. */
static sipPySlotDef slots_Phonon_SubtitleDescription[] = {
    {(void *)slot_Phonon_SubtitleDescription___eq__, eq_slot},
    {(void *)slot_Phonon_SubtitleDescription___ne__, ne_slot},
    {0, (sipPySlotType)0}
};


static PyMethodDef methods_Phonon_SubtitleDescription[] = {
    {SIP_MLNAME_CAST(sipName_description), meth_Phonon_SubtitleDescription_description, METH_VARARGS, SIP_MLDOC_CAST(doc_Phonon_SubtitleDescription_description)},
    {SIP_MLNAME_CAST(sipName_fromIndex), meth_Phonon_SubtitleDescription_fromIndex, METH_VARARGS, SIP_MLDOC_CAST(doc_Phonon_SubtitleDescription_fromIndex)},
    {SIP_MLNAME_CAST(sipName_index), meth_Phonon_SubtitleDescription_index, METH_VARARGS, SIP_MLDOC_CAST(doc_Phonon_SubtitleDescription_index)},
    {SIP_MLNAME_CAST(sipName_isValid), meth_Phonon_SubtitleDescription_isValid, METH_VARARGS, SIP_MLDOC_CAST(doc_Phonon_SubtitleDescription_isValid)},
    {SIP_MLNAME_CAST(sipName_name), meth_Phonon_SubtitleDescription_name, METH_VARARGS, SIP_MLDOC_CAST(doc_Phonon_SubtitleDescription_name)},
    {SIP_MLNAME_CAST(sipName_property), meth_Phonon_SubtitleDescription_property, METH_VARARGS, SIP_MLDOC_CAST(doc_Phonon_SubtitleDescription_property)},
    {SIP_MLNAME_CAST(sipName_propertyNames), meth_Phonon_SubtitleDescription_propertyNames, METH_VARARGS, SIP_MLDOC_CAST(doc_Phonon_SubtitleDescription_propertyNames)}
};

PyDoc_STRVAR(doc_Phonon_SubtitleDescription, "\1Phonon.SubtitleDescription()\n"
    "Phonon.SubtitleDescription(int, Dict[Union[QByteArray, bytes, bytearray]])\n"
    "Phonon.SubtitleDescription(Phonon.SubtitleDescription)");


static pyqt4ClassPluginDef plugin_Phonon_SubtitleDescription = {
    0,
    0,
    0
};


sipClassTypeDef sipTypeDef_phonon_Phonon_SubtitleDescription = {
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_Phonon__SubtitleDescription,
        {0},
        &plugin_Phonon_SubtitleDescription
    },
    {
        sipNameNr_SubtitleDescription,
        {0, 255, 0},
        7, methods_Phonon_SubtitleDescription,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_Phonon_SubtitleDescription,
    sipNameNr_PyQt4_QtCore_pyqtWrapperType,
    sipNameNr_sip_simplewrapper,
    0,
    slots_Phonon_SubtitleDescription,
    init_type_Phonon_SubtitleDescription,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_Phonon_SubtitleDescription,
    assign_Phonon_SubtitleDescription,
    array_Phonon_SubtitleDescription,
    copy_Phonon_SubtitleDescription,
    release_Phonon_SubtitleDescription,
    0,
    0,
    0,
    0,
    0,
    0,
    0
};
