/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19
 *
 * Copyright (c) 2016 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt4.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIphonon.h"

#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/abstractaudiooutput.sip"
#include <abstractaudiooutput.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/abstractvideooutput.sip"
#include <abstractvideooutput.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/audiooutput.sip"
#include <audiooutput.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/backendcapabilities.sip"
#include <backendcapabilities.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/effect.sip"
#include <effect.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/effectparameter.sip"
#include <effectparameter.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/effectwidget.sip"
#include <effectwidget.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/mediacontroller.sip"
#include <mediacontroller.h>
#line 34 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/mediacontroller.sip"
#include <mediacontroller.h>
#line 45 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/phonon/sipphononPhononMediaControllerFeatures.cpp"

#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/abstractaudiooutput.sip"
#include <abstractaudiooutput.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/abstractvideooutput.sip"
#include <abstractvideooutput.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/audiooutput.sip"
#include <audiooutput.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/backendcapabilities.sip"
#include <backendcapabilities.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/effect.sip"
#include <effect.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/effectparameter.sip"
#include <effectparameter.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/effectwidget.sip"
#include <effectwidget.h>
#line 28 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/mediacontroller.sip"
#include <mediacontroller.h>
#line 34 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/sip/phonon/mediacontroller.sip"
#include <mediacontroller.h>
#line 65 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/phonon/sipphononPhononMediaControllerFeatures.cpp"


extern "C" {static int slot_Phonon_MediaController_Features___bool__(PyObject *);}
static int slot_Phonon_MediaController_Features___bool__(PyObject *sipSelf)
{
     ::Phonon::MediaController::Features *sipCpp = reinterpret_cast< ::Phonon::MediaController::Features *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_Phonon_MediaController_Features));

    if (!sipCpp)
        return -1;


    {
        {
            int sipRes = 0;

#line 381 "sip/QtCore/qglobal.sip"
#if QT_VERSION >= 0x050000
        sipRes = (sipCpp->operator Phonon::MediaController::Features::Int() != 0);
#else
        sipRes = (sipCpp->operator int() != 0);
#endif
#line 87 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/phonon/sipphononPhononMediaControllerFeatures.cpp"

            return sipRes;
        }
    }

    return 0;
}


extern "C" {static PyObject *slot_Phonon_MediaController_Features___ne__(PyObject *,PyObject *);}
static PyObject *slot_Phonon_MediaController_Features___ne__(PyObject *sipSelf,PyObject *sipArg)
{
     ::Phonon::MediaController::Features *sipCpp = reinterpret_cast< ::Phonon::MediaController::Features *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_Phonon_MediaController_Features));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const  ::Phonon::MediaController::Features* a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_Phonon_MediaController_Features, &a0, &a0State))
        {
            bool sipRes = 0;

#line 372 "sip/QtCore/qglobal.sip"
#if QT_VERSION >= 0x050000
        sipRes = (sipCpp->operator Phonon::MediaController::Features::Int() != a0->operator Phonon::MediaController::Features::Int());
#else
        sipRes = (sipCpp->operator int() != a0->operator int());
#endif
#line 121 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/phonon/sipphononPhononMediaControllerFeatures.cpp"
            sipReleaseType(const_cast< ::Phonon::MediaController::Features *>(a0),sipType_Phonon_MediaController_Features,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_phonon, ne_slot, sipType_Phonon_MediaController_Features, sipSelf, sipArg);
}


extern "C" {static PyObject *slot_Phonon_MediaController_Features___eq__(PyObject *,PyObject *);}
static PyObject *slot_Phonon_MediaController_Features___eq__(PyObject *sipSelf,PyObject *sipArg)
{
     ::Phonon::MediaController::Features *sipCpp = reinterpret_cast< ::Phonon::MediaController::Features *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_Phonon_MediaController_Features));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const  ::Phonon::MediaController::Features* a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_Phonon_MediaController_Features, &a0, &a0State))
        {
            bool sipRes = 0;

#line 363 "sip/QtCore/qglobal.sip"
#if QT_VERSION >= 0x050000
        sipRes = (sipCpp->operator Phonon::MediaController::Features::Int() == a0->operator Phonon::MediaController::Features::Int());
#else
        sipRes = (sipCpp->operator int() == a0->operator int());
#endif
#line 161 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/phonon/sipphononPhononMediaControllerFeatures.cpp"
            sipReleaseType(const_cast< ::Phonon::MediaController::Features *>(a0),sipType_Phonon_MediaController_Features,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_phonon, eq_slot, sipType_Phonon_MediaController_Features, sipSelf, sipArg);
}


extern "C" {static PyObject *slot_Phonon_MediaController_Features___ixor__(PyObject *,PyObject *);}
static PyObject *slot_Phonon_MediaController_Features___ixor__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_Phonon_MediaController_Features)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

     ::Phonon::MediaController::Features *sipCpp = reinterpret_cast< ::Phonon::MediaController::Features *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_Phonon_MediaController_Features));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
#line 357 "sip/QtCore/qglobal.sip"
        *sipCpp = Phonon::MediaController::Features(*sipCpp ^ a0);
#line 200 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/phonon/sipphononPhononMediaControllerFeatures.cpp"

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


extern "C" {static PyObject *slot_Phonon_MediaController_Features___xor__(PyObject *,PyObject *);}
static PyObject *slot_Phonon_MediaController_Features___xor__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = NULL;

    {
         ::Phonon::MediaController::Features* a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_Phonon_MediaController_Features, &a0, &a0State, &a1))
        {
             ::Phonon::MediaController::Features*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new  ::Phonon::MediaController::Features((*a0 ^ a1));
            Py_END_ALLOW_THREADS
            sipReleaseType(a0,sipType_Phonon_MediaController_Features,a0State);

            return sipConvertFromNewType(sipRes,sipType_Phonon_MediaController_Features,NULL);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_phonon, xor_slot, NULL, sipArg0, sipArg1);
}


extern "C" {static PyObject *slot_Phonon_MediaController_Features___ior__(PyObject *,PyObject *);}
static PyObject *slot_Phonon_MediaController_Features___ior__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_Phonon_MediaController_Features)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

     ::Phonon::MediaController::Features *sipCpp = reinterpret_cast< ::Phonon::MediaController::Features *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_Phonon_MediaController_Features));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
#line 351 "sip/QtCore/qglobal.sip"
        *sipCpp = Phonon::MediaController::Features(*sipCpp | a0);
#line 274 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/phonon/sipphononPhononMediaControllerFeatures.cpp"

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


extern "C" {static PyObject *slot_Phonon_MediaController_Features___or__(PyObject *,PyObject *);}
static PyObject *slot_Phonon_MediaController_Features___or__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = NULL;

    {
         ::Phonon::MediaController::Features* a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_Phonon_MediaController_Features, &a0, &a0State, &a1))
        {
             ::Phonon::MediaController::Features*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new  ::Phonon::MediaController::Features((*a0 | a1));
            Py_END_ALLOW_THREADS
            sipReleaseType(a0,sipType_Phonon_MediaController_Features,a0State);

            return sipConvertFromNewType(sipRes,sipType_Phonon_MediaController_Features,NULL);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_phonon, or_slot, NULL, sipArg0, sipArg1);
}


extern "C" {static PyObject *slot_Phonon_MediaController_Features___iand__(PyObject *,PyObject *);}
static PyObject *slot_Phonon_MediaController_Features___iand__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_Phonon_MediaController_Features)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

     ::Phonon::MediaController::Features *sipCpp = reinterpret_cast< ::Phonon::MediaController::Features *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_Phonon_MediaController_Features));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp-> ::Phonon::MediaController::Features::operator&=(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


extern "C" {static PyObject *slot_Phonon_MediaController_Features___and__(PyObject *,PyObject *);}
static PyObject *slot_Phonon_MediaController_Features___and__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = NULL;

    {
         ::Phonon::MediaController::Features* a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_Phonon_MediaController_Features, &a0, &a0State, &a1))
        {
             ::Phonon::MediaController::Features*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new  ::Phonon::MediaController::Features((*a0 & a1));
            Py_END_ALLOW_THREADS
            sipReleaseType(a0,sipType_Phonon_MediaController_Features,a0State);

            return sipConvertFromNewType(sipRes,sipType_Phonon_MediaController_Features,NULL);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_phonon, and_slot, NULL, sipArg0, sipArg1);
}


extern "C" {static PyObject *slot_Phonon_MediaController_Features___invert__(PyObject *);}
static PyObject *slot_Phonon_MediaController_Features___invert__(PyObject *sipSelf)
{
     ::Phonon::MediaController::Features *sipCpp = reinterpret_cast< ::Phonon::MediaController::Features *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_Phonon_MediaController_Features));

    if (!sipCpp)
        return 0;


    {
        {
             ::Phonon::MediaController::Features*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new  ::Phonon::MediaController::Features(~(*sipCpp));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_Phonon_MediaController_Features,NULL);
        }
    }

    return 0;
}


extern "C" {static PyObject *slot_Phonon_MediaController_Features___int__(PyObject *);}
static PyObject *slot_Phonon_MediaController_Features___int__(PyObject *sipSelf)
{
     ::Phonon::MediaController::Features *sipCpp = reinterpret_cast< ::Phonon::MediaController::Features *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_Phonon_MediaController_Features));

    if (!sipCpp)
        return 0;


    {
        {
            int sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = *sipCpp;
            Py_END_ALLOW_THREADS

            return SIPLong_FromLong(sipRes);
        }
    }

    return 0;
}


/* Call the instance's destructor. */
extern "C" {static void release_Phonon_MediaController_Features(void *, int);}
static void release_Phonon_MediaController_Features(void *sipCppV, int)
{
    Py_BEGIN_ALLOW_THREADS

    delete reinterpret_cast< ::Phonon::MediaController::Features *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void assign_Phonon_MediaController_Features(void *, SIP_SSIZE_T, const void *);}
static void assign_Phonon_MediaController_Features(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast< ::Phonon::MediaController::Features *>(sipDst)[sipDstIdx] = *reinterpret_cast<const  ::Phonon::MediaController::Features *>(sipSrc);
}


extern "C" {static void *array_Phonon_MediaController_Features(SIP_SSIZE_T);}
static void *array_Phonon_MediaController_Features(SIP_SSIZE_T sipNrElem)
{
    return new  ::Phonon::MediaController::Features[sipNrElem];
}


extern "C" {static void *copy_Phonon_MediaController_Features(const void *, SIP_SSIZE_T);}
static void *copy_Phonon_MediaController_Features(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new  ::Phonon::MediaController::Features(reinterpret_cast<const  ::Phonon::MediaController::Features *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_Phonon_MediaController_Features(sipSimpleWrapper *);}
static void dealloc_Phonon_MediaController_Features(sipSimpleWrapper *sipSelf)
{
    if (sipIsOwnedByPython(sipSelf))
    {
        release_Phonon_MediaController_Features(sipGetAddress(sipSelf), 0);
    }
}


extern "C" {static void *init_type_Phonon_MediaController_Features(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_Phonon_MediaController_Features(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
     ::Phonon::MediaController::Features *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new  ::Phonon::MediaController::Features();
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        int a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "i", &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new  ::Phonon::MediaController::Features(a0);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        const  ::Phonon::MediaController::Features* a0;
        int a0State = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J1", sipType_Phonon_MediaController_Features, &a0, &a0State))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new  ::Phonon::MediaController::Features(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast< ::Phonon::MediaController::Features *>(a0),sipType_Phonon_MediaController_Features,a0State);

            return sipCpp;
        }
    }

    return NULL;
}


extern "C" {static int convertTo_Phonon_MediaController_Features(PyObject *, void **, int *, PyObject *);}
static int convertTo_Phonon_MediaController_Features(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
     ::Phonon::MediaController::Features **sipCppPtr = reinterpret_cast< ::Phonon::MediaController::Features **>(sipCppPtrV);

#line 390 "sip/QtCore/qglobal.sip"
// Allow an instance of the base enum whenever a Phonon::MediaController::Features is expected.

if (sipIsErr == NULL)
    return (PyObject_TypeCheck(sipPy, sipTypeAsPyTypeObject(sipType_Phonon_MediaController_Feature)) ||
            sipCanConvertToType(sipPy, sipType_Phonon_MediaController_Features, SIP_NO_CONVERTORS));

if (PyObject_TypeCheck(sipPy, sipTypeAsPyTypeObject(sipType_Phonon_MediaController_Feature)))
{
    *sipCppPtr = new Phonon::MediaController::Features(int(SIPLong_AsLong(sipPy)));

    return sipGetState(sipTransferObj);
}

*sipCppPtr = reinterpret_cast<Phonon::MediaController::Features *>(sipConvertToType(sipPy, sipType_Phonon_MediaController_Features, sipTransferObj, SIP_NO_CONVERTORS, 0, sipIsErr));

return 0;
#line 562 "/Users/saitadikonda/Desktop/TestingFolder/PyQt4_gpl_mac-4.12/phonon/sipphononPhononMediaControllerFeatures.cpp"
}


/* Define this type's Python slots. */
static sipPySlotDef slots_Phonon_MediaController_Features[] = {
    {(void *)slot_Phonon_MediaController_Features___bool__, bool_slot},
    {(void *)slot_Phonon_MediaController_Features___ne__, ne_slot},
    {(void *)slot_Phonon_MediaController_Features___eq__, eq_slot},
    {(void *)slot_Phonon_MediaController_Features___ixor__, ixor_slot},
    {(void *)slot_Phonon_MediaController_Features___xor__, xor_slot},
    {(void *)slot_Phonon_MediaController_Features___ior__, ior_slot},
    {(void *)slot_Phonon_MediaController_Features___or__, or_slot},
    {(void *)slot_Phonon_MediaController_Features___iand__, iand_slot},
    {(void *)slot_Phonon_MediaController_Features___and__, and_slot},
    {(void *)slot_Phonon_MediaController_Features___invert__, invert_slot},
    {(void *)slot_Phonon_MediaController_Features___int__, int_slot},
    {0, (sipPySlotType)0}
};

PyDoc_STRVAR(doc_Phonon_MediaController_Features, "\1Phonon.MediaController.Features()\n"
    "Phonon.MediaController.Features(Union[Phonon.MediaController.Features, Phonon.MediaController.Feature])\n"
    "Phonon.MediaController.Features(Phonon.MediaController.Features)");


static pyqt4ClassPluginDef plugin_Phonon_MediaController_Features = {
    0,
    1,
    0
};


sipClassTypeDef sipTypeDef_phonon_Phonon_MediaController_Features = {
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_Phonon__MediaController__Features,
        {0},
        &plugin_Phonon_MediaController_Features
    },
    {
        sipNameNr_Features,
        {20, 255, 0},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_Phonon_MediaController_Features,
    sipNameNr_PyQt4_QtCore_pyqtWrapperType,
    sipNameNr_sip_simplewrapper,
    0,
    slots_Phonon_MediaController_Features,
    init_type_Phonon_MediaController_Features,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_Phonon_MediaController_Features,
    assign_Phonon_MediaController_Features,
    array_Phonon_MediaController_Features,
    copy_Phonon_MediaController_Features,
    release_Phonon_MediaController_Features,
    0,
    convertTo_Phonon_MediaController_Features,
    0,
    0,
    0,
    0,
    0
};
